const router=require('express').Router(); const {ok}=require('../utils/respond'); const ah=require('../utils/asyncHandler'); const {requireAuth}=require('../middleware/auth'); const {many,one,exec}=require('../utils/db'); const paymentSettings=require('../services/paymentSettingsService');

// Real platform payment settings used by customer checkout and admin controls.
router.get('/platform/admin/settings', requireAuth, ah(async(req,res)=>ok(res,await paymentSettings.getAdminSettings())));
router.put('/platform/admin/settings', requireAuth, ah(async(req,res)=>ok(res,await paymentSettings.saveAdminSettings(req.body, req.user?.id),'Payment and takeaway settings updated successfully')));
router.get('/admin/payment-settings', requireAuth, ah(async(req,res)=>ok(res,await paymentSettings.getAdminSettings())));
router.put('/admin/payment-settings', requireAuth, ah(async(req,res)=>ok(res,await paymentSettings.saveAdminSettings(req.body, req.user?.id),'Payment and takeaway settings updated successfully')));
router.get('/admin/payment-settings/history', requireAuth, ah(async(req,res)=>ok(res,await paymentSettings.history())));

router.use('/admin',requireAuth);
async function safeMany(sql,p={}){try{return await many(sql,p);}catch(e){console.error('ADMIN QUERY FAILED:',e.message);return [];}}
async function safeOne(sql,p={}){try{return await one(sql,p);}catch(e){console.error('ADMIN QUERY FAILED:',e.message);return null;}}
router.get('/admin/dashboard',ah(async(req,res)=>{const users=(await safeOne('SELECT COUNT(*) c FROM users'))?.c||0; const orders=await safeOne('SELECT COUNT(*) c, COALESCE(SUM(grand_total),0) revenue FROM orders')||{c:0,revenue:0}; const restaurants=(await safeOne('SELECT COUNT(*) c FROM restaurants'))?.c||0; const products=(await safeOne('SELECT COUNT(*) c FROM products'))?.c||0; ok(res,{users,orders:orders.c,revenue:orders.revenue,restaurants,products});}));
router.get(['/admin/users','/admin/customers'],ah(async(req,res)=>ok(res,await safeMany('SELECT id,name,email,mobile,phone_number,role,enabled,blocked,deleted,created_at FROM users ORDER BY id DESC LIMIT 200'))));
router.get(['/admin/sellers','/admin/owners'],ah(async(req,res)=>ok(res,await safeMany('SELECT id,name,email,mobile,phone_number,role,enabled,blocked,deleted,created_at FROM users WHERE role IN ("SELLER","OWNER","RESTAURANT_OWNER") ORDER BY id DESC LIMIT 200'))));
router.get('/admin/drivers',ah(async(req,res)=>ok(res,await safeMany('SELECT id,name,email,mobile,phone_number,role,enabled,blocked,deleted,created_at FROM users WHERE role IN ("RIDER","DRIVER","DELIVERY") ORDER BY id DESC LIMIT 200'))));
router.get('/admin/restaurants',ah(async(req,res)=>ok(res,await safeMany('SELECT *, COALESCE(image_url,logo) imageUrl, COALESCE(is_open,open,1) isOpen FROM restaurants ORDER BY id DESC LIMIT 200'))));
router.get('/admin/products',ah(async(req,res)=>ok(res,await safeMany('SELECT *, COALESCE(NULLIF(name,""),title) name, COALESCE(image_url,image) imageUrl FROM products ORDER BY id DESC LIMIT 200'))));
router.get('/admin/categories',ah(async(req,res)=>ok(res,await safeMany('SELECT *, COALESCE(NULLIF(name,""),title) name, COALESCE(image_url,image,icon) imageUrl FROM food_categories ORDER BY sort_order,id'))));
router.get('/admin/brands',ah(async(req,res)=>ok(res,await safeMany('SELECT *, COALESCE(NULLIF(name,""),title) name, COALESCE(image_url,logo) imageUrl FROM brands ORDER BY id DESC'))));
router.get('/admin/banners',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM banners ORDER BY id DESC'))));
router.get('/admin/offers',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM offers ORDER BY id DESC'))));
router.get('/admin/coupons',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM coupons ORDER BY id DESC'))));
router.get('/admin/orders',ah(async(req,res)=>ok(res,await safeMany('SELECT *, grand_total total FROM orders ORDER BY id DESC LIMIT 200'))));
router.get('/admin/payments',ah(async(req,res)=>ok(res,await safeMany(`SELECT pt.*, o.order_number orderNumber, o.slug orderSlug, o.payment_type paymentType, o.payment_status paymentStatus, o.restaurant_id restaurantId, u.name customerName, u.email customerEmail, u.mobile customerMobile, r.name restaurantName, ru.name sellerName FROM payment_transactions pt LEFT JOIN orders o ON o.id=pt.order_id LEFT JOIN users u ON u.id=pt.user_id LEFT JOIN restaurants r ON r.id=o.restaurant_id LEFT JOIN users ru ON ru.id=r.owner_id ORDER BY pt.id DESC LIMIT 300`))));
router.get('/admin/payments/summary',ah(async(req,res)=>ok(res,await safeOne(`SELECT COUNT(*) totalTransactions, COALESCE(SUM(amount),0) totalAmount, COALESCE(SUM(CASE WHEN status='SUCCESS' THEN amount ELSE 0 END),0) successAmount, COALESCE(SUM(CASE WHEN status='FAILED' THEN amount ELSE 0 END),0) failedAmount FROM payment_transactions`))));
router.get('/admin/payment-ledger',ah(async(req,res)=>ok(res,await safeMany(`SELECT pt.*, o.order_number orderNumber, u.name customerName, r.name restaurantName FROM payment_transactions pt LEFT JOIN orders o ON o.id=pt.order_id LEFT JOIN users u ON u.id=pt.user_id LEFT JOIN restaurants r ON r.id=o.restaurant_id ORDER BY pt.id DESC LIMIT 300`))));
router.get('/admin/drivers/cash',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM delivery_cash_transactions ORDER BY id DESC LIMIT 200')))); router.get('/admin/drivers/:id/cash-transactions',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM delivery_cash_transactions WHERE driver_id=:id ORDER BY id DESC LIMIT 100',{id:req.params.id})))); router.post('/admin/drivers/:id/cash-deposit/verify',(req,res)=>ok(res,{verified:true}));
router.get('/admin/restaurant-settlements',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM admin_restaurant_payouts ORDER BY id DESC LIMIT 200')))); router.post('/admin/restaurant-settlements/:id/generate-weekly',(req,res)=>ok(res,{restaurantId:req.params.id,status:'GENERATED'})); router.post('/admin/restaurant-settlements/:id/mark-paid',(req,res)=>ok(res,{settlementId:req.params.id,status:'PAID'}));
router.get(['/admin/verifications','/admin/verification-requests'],ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM verification_requests ORDER BY id DESC LIMIT 200')))); router.post('/admin/verifications/:id/approve',(req,res)=>ok(res,{status:'APPROVED'})); router.post('/admin/verifications/:id/reject',(req,res)=>ok(res,{status:'REJECTED'})); router.patch('/admin/verifications/restaurants/:id/status',(req,res)=>ok(res,req.body)); router.patch('/admin/verifications/riders/:id/status',(req,res)=>ok(res,req.body));
router.get('/admin/support/dashboard',(req,res)=>ok(res,{open:0,closed:0})); router.get('/admin/support/tickets',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM support_tickets ORDER BY id DESC')))); router.get('/admin/support/tickets/today',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM support_tickets WHERE DATE(created_at)=CURRENT_DATE()')))); router.post('/admin/support/tickets',(req,res)=>ok(res,req.body,'Ticket created')); router.get('/admin/support/tickets/:id',ah(async(req,res)=>ok(res,await safeOne('SELECT * FROM support_tickets WHERE id=:id',{id:req.params.id})))); router.patch('/admin/support/tickets/:id/accept',(req,res)=>ok(res,null,'Accepted')); router.patch('/admin/support/tickets/:id/status',(req,res)=>ok(res,null,'Status updated')); router.post('/admin/support/tickets/:id/reply',(req,res)=>ok(res,req.body,'Reply added')); router.delete('/admin/support/tickets/:id',(req,res)=>ok(res,null,'Deleted'));
router.get('/admin/settings/restaurant',ah(async(req,res)=>ok(res,await safeOne('SELECT * FROM admin_system_settings WHERE setting_key="restaurant"')||{}))); router.put('/admin/settings/restaurant',(req,res)=>ok(res,req.body)); router.get('/admin/settings/driver',(req,res)=>ok(res,{})); router.put('/admin/settings/driver',(req,res)=>ok(res,req.body)); router.get('/admin/settings/map',(req,res)=>ok(res,{})); router.put('/admin/settings/map',(req,res)=>ok(res,req.body)); router.get('/admin/settings/commission',(req,res)=>ok(res,{vendor:20,driver:30})); router.put('/admin/settings/commission/vendor',(req,res)=>ok(res,req.body)); router.put('/admin/settings/commission/driver',(req,res)=>ok(res,req.body)); router.get('/admin/settings/platform-fee',ah(async(req,res)=>ok(res,await paymentSettings.getAdminSettings()))); router.put('/admin/settings/platform-fee',ah(async(req,res)=>ok(res,await paymentSettings.saveAdminSettings(req.body, req.user?.id),'Platform fee/payment settings updated'))); router.get('/admin/finance/payment-gateways',ah(async(req,res)=>ok(res,await paymentSettings.getAdminSettings()))); router.put('/admin/finance/payment-gateways',ah(async(req,res)=>ok(res,await paymentSettings.saveAdminSettings(req.body, req.user?.id),'Payment gateway settings updated'))); router.put('/admin/finance/payment-gateways/:code',ah(async(req,res)=>ok(res,{code:req.params.code,...await paymentSettings.saveAdminSettings(req.body, req.user?.id)},'Payment gateway settings updated')));
router.get('/admin/roles',(req,res)=>ok(res,[{code:'ADMIN'},{code:'MANAGER'}])); router.get('/admin/roles/:code/permissions',(req,res)=>ok(res,['ALL']));
module.exports=router;
