const router = require('express').Router();
const ah = require('../utils/asyncHandler');
const { ok, fail } = require('../utils/respond');
const { pool } = require('../utils/db');
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024, files: 6 } });

const cache = new Map();
async function cols(t){ if(cache.has(t)) return cache.get(t); try{ const [r]=await pool.execute(`SHOW COLUMNS FROM \`${t}\``); const s=new Set(r.map(x=>x.Field)); cache.set(t,s); return s; }catch{ const s=new Set(); cache.set(t,s); return s; } }
async function exec(sql,p=[]){ try{ const [r]=await pool.execute(sql,p); return r; }catch(e){ console.error('[v36-exec]', e.message, sql); return {affectedRows:0,insertId:null}; } }
async function query(sql,p=[]){ try{ const [r]=await pool.execute(sql,p); return r; }catch(e){ console.error('[v36-query]', e.message, sql); return []; } }
async function one(sql,p=[]){ const r=await query(sql,p); return r[0]||null; }
function n(v,d=0){ const x=Number(v); return Number.isFinite(x)?x:d; }
function s(v,d=''){ return String(v??d).trim(); }
function first(...values){ for(const v of values){ if(v!==undefined && v!==null && String(v).trim()!=='') return v; } return undefined; }
function bool(v,d=false){ if(v==null)return d; if(Buffer.isBuffer(v)) return v[0]===1; if(typeof v==='object'&&Array.isArray(v.data)) return Number(v.data[0])===1; if(typeof v==='boolean') return v; if(typeof v==='number') return v===1; return ['1','true','yes','on','active','available','approved','verified'].includes(String(v).toLowerCase()); }
function itemsOf(x){ if(Array.isArray(x)) return x; if(!x) return []; if(typeof x==='string'){ try{return JSON.parse(x)||[]}catch{return []} } return []; }
function page(items, req){ const per=Math.max(1,n(req.query.limit||req.query.perPage||req.query.per_page,items.length||20)); const p=Math.max(1,n(req.query.page,1)); return {items,data:items,content:items,records:items,requests:items,total:items.length,totalItems:items.length,page:p,perPage:per,per_page:per,totalPages:Math.max(1,Math.ceil(items.length/per)),total_pages:Math.max(1,Math.ceil(items.length/per)),last:true}; }
async function insertDynamic(table, data){ const c=await cols(table); const keys=Object.keys(data).filter(k=>c.has(k)&&data[k]!==undefined); if(!keys.length) return null; const sql=`INSERT INTO \`${table}\` (${keys.map(k=>`\`${k}\``).join(',')}) VALUES (${keys.map(()=>'?').join(',')})`; const r=await exec(sql, keys.map(k=>data[k])); return r.insertId; }
async function updateDynamic(table,id,data){ const c=await cols(table); const keys=Object.keys(data).filter(k=>c.has(k)&&data[k]!==undefined); if(!keys.length) return; await exec(`UPDATE \`${table}\` SET ${keys.map(k=>`\`${k}\`=?`).join(',')} WHERE id=?`,[...keys.map(k=>data[k]),id]); }
async function ensure(){
 await exec(`CREATE TABLE IF NOT EXISTS franchise_requests (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  owner_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NULL,
  business_name VARCHAR(255) NULL,
  address TEXT NULL, city VARCHAR(120) NULL, state VARCHAR(120) NULL, pincode VARCHAR(20) NULL,
  latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL,
  query TEXT NULL, investment_budget DECIMAL(12,2) NULL,
  preferred_contact_method VARCHAR(40) NULL DEFAULT 'PHONE', status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  admin_note TEXT NULL, contacted_at DATETIME(6) NULL, approved_restaurant_id BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
 )`);
 await exec(`CREATE TABLE IF NOT EXISTS seller_payout_accounts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT NULL, restaurant_id BIGINT NULL,
  account_holder_name VARCHAR(255) NULL, upi_id VARCHAR(255) NULL, bank_name VARCHAR(255) NULL,
  account_number VARCHAR(255) NULL, ifsc_code VARCHAR(50) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'PENDING', verified BIT(1) NOT NULL DEFAULT b'0', verified_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
 )`);
 await exec(`CREATE TABLE IF NOT EXISTS restaurant_payout_actions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, restaurant_id BIGINT NOT NULL, seller_id BIGINT NULL,
  action_type VARCHAR(40) NOT NULL, amount DECIMAL(12,2) NOT NULL DEFAULT 0, upi_id VARCHAR(255) NULL,
  note TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
 )`);
 await exec(`CREATE TABLE IF NOT EXISTS seller_food_requests (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT NULL, restaurant_id BIGINT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NULL,
  description TEXT NULL, category_id BIGINT NULL, category_name VARCHAR(255) NULL, food_type VARCHAR(80) NULL,
  price DECIMAL(12,2) NULL, discount_price DECIMAL(12,2) NULL, stock_quantity INT NULL, image_url TEXT NULL,
  pricing_json JSON NULL, raw_json JSON NULL, status VARCHAR(40) NOT NULL DEFAULT 'PENDING', admin_note TEXT NULL,
  approved_product_id BIGINT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
 )`);
 await exec(`CREATE TABLE IF NOT EXISTS product_admin_approval (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, product_id BIGINT NOT NULL, seller_food_request_id BIGINT NULL,
  approval_status VARCHAR(40) NOT NULL DEFAULT 'APPROVED', approved_by BIGINT NULL, approved_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
 )`);
 const rc=await cols('restaurants'); if(rc.size){ const adds=[]; if(!rc.has('payout_alert_status')) adds.push('ADD COLUMN payout_alert_status VARCHAR(40) NULL DEFAULT \'ACTIVE\''); if(!rc.has('last_payout_at')) adds.push('ADD COLUMN last_payout_at DATETIME(6) NULL'); if(!rc.has('upi_id')) adds.push('ADD COLUMN upi_id VARCHAR(255) NULL'); if(!rc.has('bank_details')) adds.push('ADD COLUMN bank_details TEXT NULL'); if(adds.length) { await exec(`ALTER TABLE restaurants ${adds.join(', ')}`); cache.delete('restaurants'); } }
 const pc=await cols('products'); if(pc.size){ const adds=[]; if(!pc.has('approval_status')) adds.push('ADD COLUMN approval_status VARCHAR(40) NULL DEFAULT \'APPROVED\''); if(!pc.has('admin_approved')) adds.push('ADD COLUMN admin_approved BIT(1) NOT NULL DEFAULT b\'1\''); if(adds.length){ await exec(`ALTER TABLE products ${adds.join(', ')}`); cache.delete('products'); } }
}
ensure().catch(e=>console.error('[v36-init]',e.message));
function normFranchise(x){ return { ...x, id:x.id, ownerName:x.owner_name, businessName:x.business_name, investmentBudget:n(x.investment_budget), preferredContactMethod:x.preferred_contact_method, adminNote:x.admin_note, approvedRestaurantId:x.approved_restaurant_id, createdAt:x.created_at, updatedAt:x.updated_at }; }
async function restaurantsUnderMrBreado(){ const rows=await query(`SELECT r.*, COALESCE(SUM(CASE WHEN o.status IN ('DELIVERED','COMPLETED') THEN COALESCE(o.grand_total,o.total_amount,0) ELSE 0 END),0) gross_sales, COUNT(DISTINCT o.id) total_orders, COUNT(DISTINCT p.id) total_products FROM restaurants r LEFT JOIN orders o ON o.restaurant_id=r.id LEFT JOIN products p ON p.restaurant_id=r.id WHERE LOWER(COALESCE(r.name,'')) LIKE '%mr breado%' OR LOWER(COALESCE(r.name,'')) LIKE '%mr_breado%' OR LOWER(COALESCE(r.parent_brand,'')) LIKE '%mr breado%' OR LOWER(COALESCE(r.outlet_type,'')) LIKE '%franchise%' GROUP BY r.id ORDER BY r.id DESC LIMIT 300`); return rows.map(r=>({...r, name:r.name, city:first(r.city,r.address,''), grossSales:n(r.gross_sales), totalOrders:n(r.total_orders), totalProducts:n(r.total_products), verificationStatus:first(r.verification_status,r.verificationStatus,'UNVERIFIED'), payoutAlertStatus:first(r.payout_alert_status,'ACTIVE'), upiId:r.upi_id})); }
router.post(['/seller/franchise/requests','/franchise/requests','/auth/franchise-request','/seller/outlet/request'], ah(async(req,res)=>{ await ensure(); const b=req.body||{}; const owner=s(first(b.ownerName,b.owner_name,b.name,b.fullName,b.owner)); const phone=s(first(b.phone,b.mobile,b.mobileNumber,b.phoneNumber)); if(!owner||!phone) return fail(res,'Owner name and phone are required',400); const id=await insertDynamic('franchise_requests',{ owner_name:owner, phone, email:s(first(b.email,b.emailAddress)), business_name:s(first(b.businessName,b.business_name,b.restaurantName,b.outletName,'Mr Breado Outlet')), address:s(first(b.address,b.location,b.restaurantAddress)), city:s(b.city), state:s(b.state), pincode:s(b.pincode), latitude:first(b.latitude,b.lat,null), longitude:first(b.longitude,b.lng,b.long,null), query:s(first(b.query,b.message,b.note,b.businessPlan)), investment_budget:n(first(b.investmentBudget,b.investment_budget,b.budget),0)||null, preferred_contact_method:s(first(b.preferredContactMethod,b.preferred_contact_method,'PHONE')), status:'PENDING', created_at:new Date(), updated_at:new Date() }); ok(res,{id,status:'PENDING'},'Franchise request submitted',201); }));
router.get(['/admin/franchise-requests','/admin/outlets/franchise-requests','/admin/franchise/leads'], ah(async(req,res)=>{ await ensure(); const rows=await query(`SELECT * FROM franchise_requests ORDER BY FIELD(status,'PENDING','CONTACTED','APPROVED','REJECTED'), id DESC LIMIT 500`); ok(res,page(rows.map(normFranchise),req),'Franchise requests loaded'); }));
router.patch(['/admin/franchise-requests/:id/status','/admin/franchise/leads/:id/status'], ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const status=s(first(req.body?.status,req.query.status,'CONTACTED')).toUpperCase(); await exec(`UPDATE franchise_requests SET status=?, admin_note=?, contacted_at=CASE WHEN ? IN ('CONTACTED','APPROVED') THEN NOW(6) ELSE contacted_at END WHERE id=?`,[status,s(first(req.body?.note,req.body?.adminNote,'')),status,id]); ok(res,{id,status},'Franchise request updated'); }));
router.post('/admin/franchise-requests/:id/contact', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); await exec(`UPDATE franchise_requests SET status='CONTACTED', admin_note=?, contacted_at=NOW(6) WHERE id=?`,[s(req.body?.note||'Contacted from admin panel'),id]); ok(res,{id,status:'CONTACTED'},'Marked contacted'); }));
router.get(['/admin/outlets','/admin/franchise-outlets','/admin/mr-breado/outlets'], ah(async(req,res)=>ok(res,page(await restaurantsUnderMrBreado(),req),'Franchise outlets loaded')));
router.get('/admin/outlets/:id/inventory', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const rows=await query(`SELECT p.*, COALESCE(i.stock_quantity,p.stock_quantity,0) stock_quantity FROM products p LEFT JOIN franchise_outlet_inventory i ON i.product_id=p.id AND i.restaurant_id=? WHERE p.restaurant_id=? OR LOWER(COALESCE(p.tags,'')) LIKE '%mr-breado%' OR LOWER(COALESCE(p.tags,'')) LIKE '%mr breado%' ORDER BY p.id DESC LIMIT 200`,[id,id]); ok(res,rows.map(p=>({...p,id:p.id,title:first(p.title,p.name),name:first(p.name,p.title),imageUrl:first(p.image_url,p.image),stockQuantity:n(p.stock_quantity),price:n(p.price||p.selling_price)})),'Outlet inventory loaded'); }));
router.get(['/seller/payout-account','/seller/payout/accounts'], ah(async(req,res)=>{ await ensure(); const sellerId=first(req.query.sellerId,req.user?.id); const restaurantId=first(req.query.restaurantId,req.user?.restaurantId,req.user?.restaurant_id); let row=null; if(sellerId) row=await one('SELECT * FROM seller_payout_accounts WHERE seller_id=? ORDER BY id DESC LIMIT 1',[sellerId]); if(!row&&restaurantId) row=await one('SELECT * FROM seller_payout_accounts WHERE restaurant_id=? ORDER BY id DESC LIMIT 1',[restaurantId]); ok(res,row?{...row,upiId:row.upi_id,accountHolderName:row.account_holder_name,bankName:row.bank_name,accountNumber:row.account_number,ifscCode:row.ifsc_code,verified:bool(row.verified)}:{status:'NOT_ADDED',verified:false},'Seller payout account loaded'); }));
router.post(['/seller/payout-account','/seller/payout/accounts'], ah(async(req,res)=>{ await ensure(); const b=req.body||{}; const sellerId=first(b.sellerId,b.seller_id,req.user?.id,null); const restaurantId=first(b.restaurantId,b.restaurant_id,req.user?.restaurantId,req.user?.restaurant_id,null); const data={seller_id:sellerId,restaurant_id:restaurantId,account_holder_name:s(first(b.accountHolderName,b.account_holder_name,b.name)),upi_id:s(first(b.upiId,b.upi_id)),bank_name:s(first(b.bankName,b.bank_name)),account_number:s(first(b.accountNumber,b.account_number)),ifsc_code:s(first(b.ifscCode,b.ifsc_code)),status:'PENDING',verified:0,created_at:new Date(),updated_at:new Date()}; const existing = sellerId ? await one('SELECT id FROM seller_payout_accounts WHERE seller_id=? ORDER BY id DESC LIMIT 1',[sellerId]) : null; let id=existing?.id; if(id) await updateDynamic('seller_payout_accounts',id,{...data,created_at:undefined}); else id=await insertDynamic('seller_payout_accounts',data); if(restaurantId && data.upi_id) await updateDynamic('restaurants',restaurantId,{upi_id:data.upi_id,bank_details:JSON.stringify(data)}); ok(res,{id,status:'PENDING',verified:false},'Payout details saved'); }));
router.get(['/admin/seller-payout-accounts','/admin/payout-accounts'], ah(async(req,res)=>{ await ensure(); const rows=await query(`SELECT a.*, u.name seller_name, u.phone seller_phone, r.name restaurant_name FROM seller_payout_accounts a LEFT JOIN users u ON u.id=a.seller_id LEFT JOIN restaurants r ON r.id=a.restaurant_id ORDER BY FIELD(a.status,'PENDING','VERIFIED','REJECTED'), a.id DESC LIMIT 500`); ok(res,page(rows.map(x=>({...x,upiId:x.upi_id,accountHolderName:x.account_holder_name,bankName:x.bank_name,accountNumber:x.account_number,ifscCode:x.ifsc_code,sellerName:x.seller_name,restaurantName:x.restaurant_name,verified:bool(x.verified)})),req),'Payout accounts loaded'); }));
router.patch(['/admin/seller-payout-accounts/:id/verify','/admin/seller-payout-accounts/:id/status'], ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const approved=String(first(req.body?.approved,req.body?.verified,req.body?.status,'true')).toUpperCase(); const okStatus=approved==='TRUE'||approved==='1'||approved==='VERIFIED'||approved==='APPROVED'; await exec(`UPDATE seller_payout_accounts SET status=?, verified=?, verified_at=CASE WHEN ?=1 THEN NOW(6) ELSE verified_at END WHERE id=?`,[okStatus?'VERIFIED':'REJECTED',okStatus?1:0,okStatus?1:0,id]); ok(res,{id,status:okStatus?'VERIFIED':'REJECTED'},'Payout account updated'); }));
async function restaurantPayable(restaurantId){ const r=await one(`SELECT COALESCE(SUM(net_payable),0) payable FROM restaurant_payout_ledgers WHERE restaurant_id=? AND COALESCE(settlement_status,'PENDING') NOT IN ('PAID','SETTLED')`,[restaurantId]); return n(r?.payable); }
router.get('/admin/restaurants/:id/payout-summary', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const r=await one('SELECT * FROM restaurants WHERE id=?',[id]); const acc=await one('SELECT * FROM seller_payout_accounts WHERE restaurant_id=? OR seller_id=? ORDER BY id DESC LIMIT 1',[id,r?.owner_id||r?.seller_id||0]); ok(res,{restaurantId:id,payableAmount:await restaurantPayable(id),upiId:first(acc?.upi_id,r?.upi_id),payoutAlertStatus:first(r?.payout_alert_status,'ACTIVE'),account:acc},'Restaurant payout summary loaded'); }));
router.patch('/admin/restaurants/:id/payout-alert', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const status=s(first(req.body?.status,req.body?.action,'PAUSED')).toUpperCase(); await updateDynamic('restaurants',id,{payout_alert_status:status}); await insertDynamic('restaurant_payout_actions',{restaurant_id:id,action_type:status,amount:0,note:s(req.body?.note),created_at:new Date()}); ok(res,{restaurantId:id,status},'Payout alert updated'); }));
router.post('/admin/restaurants/:id/payout/pay', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const amount=n(first(req.body?.amount, await restaurantPayable(id))); const r=await one('SELECT * FROM restaurants WHERE id=?',[id]); const acc=await one('SELECT * FROM seller_payout_accounts WHERE restaurant_id=? OR seller_id=? ORDER BY id DESC LIMIT 1',[id,r?.owner_id||r?.seller_id||0]); await exec(`UPDATE restaurant_payout_ledgers SET settlement_status='PAID', paid_at=NOW(6) WHERE restaurant_id=? AND COALESCE(settlement_status,'PENDING') NOT IN ('PAID','SETTLED')`,[id]); await updateDynamic('restaurants',id,{last_payout_at:new Date(),payout_alert_status:'PAID'}); await insertDynamic('restaurant_payout_actions',{restaurant_id:id,seller_id:r?.owner_id||r?.seller_id||null,action_type:'PAID',amount,upi_id:first(req.body?.upiId,acc?.upi_id,r?.upi_id),note:s(req.body?.note||'Paid from admin panel'),created_at:new Date()}); ok(res,{restaurantId:id,amount,upiId:first(req.body?.upiId,acc?.upi_id,r?.upi_id),status:'PAID'},'Restaurant payout marked paid'); }));
function categoryPricing(b){ return { smallSizePrice:first(b.smallSizePrice,b.small_price,b.smallPrice), mediumSizePrice:first(b.mediumSizePrice,b.medium_price,b.mediumPrice), largeSizePrice:first(b.largeSizePrice,b.large_price,b.largePrice), cake500gmPrice:first(b.cake500gmPrice,b.cake_500gm_price,b.base500gmPrice), cakeExtraHalfKgPrice:first(b.cakeExtraHalfKgPrice,b.cake_extra_half_kg_price), cakeMinKg:first(b.cakeMinKg,b.cake_min_kg), cakeMaxKg:first(b.cakeMaxKg,b.cake_max_kg), allowCustomWeight:bool(first(b.allowCustomWeight,b.allow_custom_weight),false), allowCakeMessage:bool(first(b.allowCakeMessage,b.allow_cake_message),false), cakeMessageCharge:first(b.cakeMessageCharge,b.cake_message_charge) }; }
router.post(['/seller/food-requests','/seller/products/request','/seller/products/approval-request'], upload.any(), ah(async(req,res)=>{ await ensure(); const b=req.body||{}; const title=s(first(b.title,b.name,b.productName)); if(!title) return fail(res,'Food title is required',400); const id=await insertDynamic('seller_food_requests',{ seller_id:first(b.sellerId,b.seller_id,req.user?.id,null), restaurant_id:first(b.restaurantId,b.restaurant_id,req.user?.restaurantId,req.user?.restaurant_id,null), title, subtitle:s(first(b.subtitle,b.shortDescription)), description:s(b.description), category_id:first(b.categoryId,b.category_id,b.foodCategoryId,b.menuCategoryId,null), category_name:s(first(b.categoryName,b.category,b.foodCategoryName)), food_type:s(first(b.foodType,b.food_type)), price:n(b.price), discount_price:first(b.discountPrice,b.discount_price,null), stock_quantity:n(first(b.stockQuantity,b.stock_quantity,b.stock),0), image_url:s(first(b.imageUrl,b.image_url,b.image)), pricing_json:JSON.stringify(categoryPricing(b)), raw_json:JSON.stringify(b), status:'PENDING', created_at:new Date(), updated_at:new Date() }); ok(res,{id,status:'PENDING'},'Food request sent to admin for approval',201); }));
router.get(['/admin/food-requests','/admin/seller-food-requests'], ah(async(req,res)=>{ await ensure(); const rows=await query(`SELECT f.*, r.name restaurant_name, u.name seller_name FROM seller_food_requests f LEFT JOIN restaurants r ON r.id=f.restaurant_id LEFT JOIN users u ON u.id=f.seller_id ORDER BY FIELD(f.status,'PENDING','APPROVED','REJECTED'), f.id DESC LIMIT 500`); ok(res,page(rows.map(x=>({...x,restaurantName:x.restaurant_name,sellerName:x.seller_name,pricing:itemsOf(x.pricing_json),raw:itemsOf(x.raw_json),createdAt:x.created_at})),req),'Food approval requests loaded'); }));
router.patch('/admin/food-requests/:id/status', ah(async(req,res)=>{ await ensure(); const id=n(req.params.id); const status=s(first(req.body?.status,'APPROVED')).toUpperCase(); const f=await one('SELECT * FROM seller_food_requests WHERE id=?',[id]); if(!f) return fail(res,'Food request not found',404); let productId=f.approved_product_id; if(status==='APPROVED'&&!productId){ productId=await insertDynamic('products',{name:f.title,title:f.title,subtitle:f.subtitle,description:f.description,price:f.price,selling_price:f.price,discount_price:f.discount_price,restaurant_id:f.restaurant_id,category_id:f.category_id,food_category_id:f.category_id,menu_category_id:f.category_id,image_url:f.image_url,image:f.image_url,stock_quantity:f.stock_quantity,available:1,active:1,visible:1,admin_approved:1,approval_status:'APPROVED',created_at:new Date(),updated_at:new Date()}); await insertDynamic('product_admin_approval',{product_id:productId,seller_food_request_id:id,approval_status:'APPROVED',approved_at:new Date()}); }
 await updateDynamic('seller_food_requests',id,{status,approved_product_id:productId,admin_note:s(first(req.body?.note,req.body?.adminNote,'')),updated_at:new Date()}); ok(res,{id,status,productId},'Food request updated'); }));
module.exports = router;
