const router=require('express').Router(); const multer=require('multer'); const cloudinary=require('cloudinary').v2; const { cloudinary:cfg, limits }=require('../config/env'); const {ok}=require('../utils/respond'); const ah=require('../utils/asyncHandler'); const {requireAuth,optionalAuth}=require('../middleware/auth'); const {many,one,exec}=require('../utils/db');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:limits.imageBytes}}); if(cfg.cloudName) cloudinary.config({cloud_name:cfg.cloudName,api_key:cfg.apiKey,api_secret:cfg.apiSecret});
async function uploadFile(file,folder){ if(!file) return null; if(!cfg.cloudName) return {url:`/uploads/${file.originalname}`,publicId:file.originalname,local:true}; return await new Promise((resolve,reject)=>{const s=cloudinary.uploader.upload_stream({folder},(e,r)=>e?reject(e):resolve({url:r.secure_url,publicId:r.public_id})); s.end(file.buffer);});}
router.post(['/admin/uploads/offer-image','/admin/uploads/product-image','/admin/uploads/restaurant-image'],requireAuth,upload.single('file'),ah(async(req,res)=>ok(res,await uploadFile(req.file,'mr-breado'),'Uploaded')));
router.get('/notifications',requireAuth,ah(async(req,res)=>ok(res,await many('SELECT * FROM notifications WHERE user_id IS NULL OR user_id=:uid OR role=:role ORDER BY id DESC LIMIT 100',{uid:req.user.id,role:req.user.role}))));
router.patch('/notifications/:id/read',requireAuth,ah(async(req,res)=>{await exec('UPDATE notifications SET is_read=1 WHERE id=:id',{id:req.params.id}); ok(res,null,'Notification read');})); router.patch('/notifications/read-all',requireAuth,ah(async(req,res)=>{await exec('UPDATE notifications SET is_read=1 WHERE user_id=:uid OR role=:role',{uid:req.user.id,role:req.user.role}); ok(res,null,'All read');})); router.delete('/notifications/:id',requireAuth,ah(async(req,res)=>{await exec('DELETE FROM notifications WHERE id=:id',{id:req.params.id}); ok(res,null,'Deleted');})); router.get('/notifications/settings',requireAuth,(req,res)=>ok(res,{push:true,email:true,sms:false})); router.put('/notifications/settings',requireAuth,(req,res)=>ok(res,req.body,'Settings updated'));
router.post(['/admin/notifications/send','/admin/notifications/send-to-customers','/admin/notifications/send-to-sellers','/admin/notifications/send-to-drivers'],requireAuth,ah(async(req,res)=>{await exec('INSERT INTO notifications(role,title,message,type) VALUES(:role,:title,:message,:type)',{role:req.path.includes('customers')?'USER':req.path.includes('sellers')?'SELLER':req.path.includes('drivers')?'DRIVER':null,title:req.body.title||'Notification',message:req.body.message||'',type:req.body.type||'ADMIN'}); ok(res,{sent:true},'Notification sent');}));
router.post('/support/tickets',optionalAuth,ah(async(req,res)=>{const r=await exec(`INSERT INTO support_tickets(user_id,issue,description,status,ticket_number,user_type,deleted,created_at) VALUES(:uid,:s,:m,'PENDING',:ticket,:userType,0,NOW())`,{uid:req.user?.id||null,s:req.body.subject||req.body.issue||'Support',m:req.body.message||req.body.description||'',ticket:'TCK-'+Date.now(),userType:req.user?.role||'CUSTOMER'}); ok(res,{id:r.insertId},'Ticket created',201);}));
router.post('/reviews',requireAuth,ah(async(req,res)=>{const b=req.body; const r=await exec('INSERT INTO reviews(user_id,restaurant_id,product_id,rating,comment,type,approved,deleted,created_at) VALUES(:uid,:rid,:pid,:rating,:comment,:type,1,0,NOW())',{uid:req.user.id,rid:b.restaurantId||null,pid:b.productId||null,rating:b.rating||5,comment:b.comment||'',type:b.productId?'PRODUCT':'RESTAURANT'}); ok(res,{id:r.insertId},'Review added',201);}));
router.get('/products/:id/reviews',ah(async(req,res)=>ok(res,await many('SELECT * FROM reviews WHERE product_id=:id ORDER BY id DESC',{id:req.params.id})))); router.get('/restaurants/:id/reviews',ah(async(req,res)=>ok(res,await many('SELECT * FROM reviews WHERE restaurant_id=:id ORDER BY id DESC',{id:req.params.id})))); router.get('/user/reviews',requireAuth,ah(async(req,res)=>ok(res,await many('SELECT * FROM reviews WHERE user_id=:id ORDER BY id DESC',{id:req.user.id}))));
router.get('/reviews/order/:id/eligibility',requireAuth,ah(async(req,res)=>{const o=await one('SELECT * FROM orders WHERE id=:id AND user_id=:uid',{id:req.params.id,uid:req.user.id}); ok(res,{eligible:!!o && o.status==='DELIVERED',order:o});})); router.post('/reviews/order/:id',requireAuth,ah(async(req,res)=>{const b=req.body; const r=await exec(`INSERT INTO reviews(user_id,order_id,restaurant_id,rating,comment,type,approved,deleted,created_at) VALUES(:uid,:oid,:rid,:rating,:comment,'RESTAURANT',1,0,NOW())`,{uid:req.user.id,oid:req.params.id,rid:b.restaurantId||null,rating:b.rating||5,comment:b.comment||''}); ok(res,{id:r.insertId},'Order reviewed');}));
router.post('/favorites/restaurants/:id',requireAuth,(req,res)=>ok(res,{restaurantId:req.params.id,favorite:true})); router.delete('/favorites/restaurants/:id',requireAuth,(req,res)=>ok(res,{restaurantId:req.params.id,favorite:false})); router.get('/favorites/restaurants',requireAuth,(req,res)=>ok(res,[])); router.post('/favorites/products/:id',requireAuth,(req,res)=>ok(res,{productId:req.params.id,favorite:true})); router.delete('/favorites/products/:id',requireAuth,(req,res)=>ok(res,{productId:req.params.id,favorite:false})); router.get('/favorites/products',requireAuth,(req,res)=>ok(res,[]));
router.post('/search-history',requireAuth,(req,res)=>ok(res,req.body,'Saved')); router.get('/search-history',requireAuth,(req,res)=>ok(res,[])); router.delete('/search-history',requireAuth,(req,res)=>ok(res,null,'Cleared'));
router.post('/user/orders/:id/restaurant-report',requireAuth,(req,res)=>ok(res,{id:Date.now(),...req.body},'Report submitted')); router.get('/user/restaurant-reports',requireAuth,(req,res)=>ok(res,[])); router.get('/seller/restaurant-reports',requireAuth,(req,res)=>ok(res,[])); router.get('/admin/restaurant-reports',requireAuth,(req,res)=>ok(res,[])); router.patch('/admin/restaurant-reports/:id/status',requireAuth,(req,res)=>ok(res,req.body,'Status updated'));
router.get('/user/profile',requireAuth,(req,res)=>ok(res,{user:req.user})); router.post('/user/profile',requireAuth,(req,res)=>ok(res,req.body,'Profile saved')); router.put('/user/profile',requireAuth,(req,res)=>ok(res,req.body,'Profile updated')); router.put('/user/change-password',requireAuth,(req,res)=>ok(res,null,'Password changed')); router.delete('/user/account',requireAuth,(req,res)=>ok(res,null,'Account deletion requested'));
router.get('/admin/reviews',requireAuth,ah(async(req,res)=>ok(res,await many('SELECT * FROM reviews ORDER BY id DESC'))));
router.post('/admin/customer-messages/send',requireAuth,(req,res)=>ok(res,{sent:true},'Message sent')); router.post('/admin/seller-messages',requireAuth,(req,res)=>ok(res,{sent:true},'Message sent')); router.get('/admin/seller-messages',requireAuth,(req,res)=>ok(res,[]));
router.get('/health',(req,res)=>ok(res,{status:'UP',service:'mr-breado-node-backend'}));
module.exports=router;
