const router=require('express').Router(); const {ok,fail}=require('../utils/respond'); const ah=require('../utils/asyncHandler'); const {requireAuth}=require('../middleware/auth'); const {many,one,exec,slugify}=require('../utils/db');
router.use((req,res,next)=>{ const p=req.path; if(!p.startsWith('/seller') && !p.startsWith('/delivery') && !p.startsWith('/rider') && !p.startsWith('/user/orders')) return next('router'); return next(); });
router.use(requireAuth);
async function safeMany(sql,p={}){try{return await many(sql,p);}catch(e){console.error('OPS QUERY FAILED:',e.message);return [];}}
async function safeOne(sql,p={}){try{return await one(sql,p);}catch(e){console.error('OPS QUERY FAILED:',e.message);return null;}}
async function sellerRestaurant(user){let r=await safeOne('SELECT * FROM restaurants WHERE owner_id=:id LIMIT 1',{id:user.id}); if(!r){const rr=await exec('INSERT INTO restaurants(owner_id,name,slug,verification_status,visibility_status,status,created_at) VALUES(:id,:name,:slug,"PENDING","VISIBLE","PENDING",NOW())',{id:user.id,name:`${user.name||'Seller'} Restaurant`,slug:`seller-${user.id}`}); r=await one('SELECT * FROM restaurants WHERE id=:id',{id:rr.insertId});} return r;}
router.get('/seller/restaurant',ah(async(req,res)=>ok(res,await sellerRestaurant(req.user))));
router.put('/seller/restaurant',ah(async(req,res)=>{const b=req.body; let r=await sellerRestaurant(req.user); await exec('UPDATE restaurants SET name=COALESCE(:name,name), slug=COALESCE(:slug,slug), description=COALESCE(:description,description), image_url=COALESCE(:image,image_url), logo=COALESCE(:image,logo), address=COALESCE(:address,address), latitude=COALESCE(:lat,latitude), longitude=COALESCE(:lng,longitude), is_open=COALESCE(:open,is_open), open=COALESCE(:open,open), updated_at=NOW() WHERE id=:id',{id:r.id,name:b.name||null,slug:b.slug|| (b.name?slugify(b.name):null),description:b.description||null,image:b.imageUrl||b.image_url||b.logo||null,address:b.address||null,lat:b.latitude||null,lng:b.longitude||null,open:b.isOpen??b.open??null}); ok(res,await one('SELECT * FROM restaurants WHERE id=:id',{id:r.id}),'Restaurant updated');}));
router.patch('/seller/restaurant/status',ah(async(req,res)=>{const isOpen=req.body.isOpen ?? req.body.open ?? req.body.status==='OPEN'; await exec('UPDATE restaurants SET is_open=:isOpen, open=:isOpen WHERE owner_id=:id',{isOpen,id:req.user.id}); ok(res,{isOpen},'Status updated');}));
router.get('/seller/products',ah(async(req,res)=>{const r=await sellerRestaurant(req.user); ok(res,await safeMany('SELECT *, COALESCE(NULLIF(name,""),title) name, COALESCE(image_url,image) imageUrl FROM products WHERE restaurant_id=:rid ORDER BY id DESC',{rid:r.id}));}));
router.post('/seller/products',ah(async(req,res)=>{const rest=await sellerRestaurant(req.user); const b=req.body; const title=b.name||b.title||'Product'; const slug=slugify(b.slug||title)+'-'+Date.now(); const r=await exec('INSERT INTO products(restaurant_id,category_id,food_category_id,menu_category_id,name,title,slug,description,image_url,image,price,discount_price,veg,available,stock,stock_quantity,created_at) VALUES(:rid,:cat,:cat,:menu,:name,:name,:slug,:description,:image,:image,:price,:discount,:veg,:available,:stock,:stock,NOW())',{rid:rest.id,cat:b.categoryId||b.category_id||b.foodCategoryId||null,menu:b.menuCategoryId||b.menu_category_id||null,name:title,slug,description:b.description||'',image:b.imageUrl||b.image_url||b.image||'',price:b.price||0,discount:b.discountPrice||b.discount_price||null,veg:b.veg??true,available:b.available??true,stock:b.stock??b.stockQuantity??100}); ok(res,await one('SELECT * FROM products WHERE id=:id',{id:r.insertId}),'Product created',201);}));
router.put('/seller/products/:id',ah(async(req,res)=>{const b=req.body; await exec('UPDATE products SET name=COALESCE(:name,name), title=COALESCE(:name,title), description=COALESCE(:description,description), image_url=COALESCE(:image,image_url), image=COALESCE(:image,image), price=COALESCE(:price,price), discount_price=COALESCE(:discount,discount_price), stock=COALESCE(:stock,stock), stock_quantity=COALESCE(:stock,stock_quantity), updated_at=NOW() WHERE id=:id',{id:req.params.id,name:b.name||b.title||null,description:b.description||null,image:b.imageUrl||b.image||null,price:b.price??null,discount:b.discountPrice??b.discount_price??null,stock:b.stock??b.stockQuantity??null}); ok(res,await one('SELECT * FROM products WHERE id=:id',{id:req.params.id}),'Product updated');}));
router.patch('/seller/products/:id/availability',ah(async(req,res)=>{const available=req.body.available ?? req.body.isAvailable ?? true; await exec('UPDATE products SET available=:available WHERE id=:id',{id:req.params.id,available}); ok(res,{id:req.params.id,available},'Availability updated');}));
async function orderDetail(id){const o=await safeOne('SELECT *, grand_total total FROM orders WHERE id=:id OR slug=:id OR order_number=:id',{id}); if(!o) return null; const items=await safeMany('SELECT * FROM order_items WHERE order_id=:id',{id:o.id}); const assignment=await safeOne('SELECT * FROM delivery_assignments WHERE order_id=:id ORDER BY id DESC LIMIT 1',{id:o.id}); return {...o,items,assignment};}
router.get(['/seller/orders','/admin/mr-breado/orders'],ah(async(req,res)=>ok(res,await safeMany('SELECT *, grand_total total FROM orders ORDER BY id DESC LIMIT 100'))));
router.get(['/seller/orders/export.csv','/admin/mr-breado/orders/export.csv'],ah(async(req,res)=>{res.type('text/csv').send('id,slug,status,total\n');}));
router.get(['/seller/orders/:id','/admin/mr-breado/orders/:id'],ah(async(req,res)=>{const d=await orderDetail(req.params.id); if(!d)return fail(res,'Order not found',404); ok(res,d);}));
router.get(['/seller/orders/:id/invoice.pdf','/admin/mr-breado/orders/:id/invoice.pdf'],(req,res)=>res.type('application/pdf').send(Buffer.from('%PDF-1.4\n% invoice\n')));
router.post(['/seller/orders/:id/invoice/send-to-customer','/admin/mr-breado/orders/:id/invoice/send-to-customer'],(req,res)=>ok(res,{sent:true},'Invoice sent'));
for (const [path,status] of [['accept','ACCEPTED'],['reject','REJECTED'],['preparing','PREPARING'],['ready','READY_FOR_PICKUP']]) router.post([`/seller/orders/:id/${path}`,`/admin/mr-breado/orders/:id/${path}`],ah(async(req,res)=>{await exec('UPDATE orders SET status=:status,seller_responded_at=NOW(),seller_accepted=:accepted WHERE id=:id',{status,accepted:status==='ACCEPTED'||status==='PREPARING'||status==='READY_FOR_PICKUP',id:req.params.id}); ok(res,await orderDetail(req.params.id),`Order ${status.toLowerCase()}`);}));
router.put('/seller/orders/:id/status',ah(async(req,res)=>{const status=req.body.status||'ACCEPTED'; await exec('UPDATE orders SET status=:status,updated_at=NOW() WHERE id=:id',{status,id:req.params.id}); ok(res,await orderDetail(req.params.id),'Order status updated');}));
router.get('/seller/reviews',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM reviews ORDER BY id DESC'))));
router.get('/seller/messages',(req,res)=>ok(res,[])); router.patch('/seller/messages/:id/read',(req,res)=>ok(res,null,'Read'));
router.post(['/seller/verification/restaurant','/seller/verification/restaurant/:id'], (req,res)=>ok(res,{status:'PENDING'},'Verification submitted'));
router.get('/seller/verification/status',(req,res)=>ok(res,{status:'PENDING'}));
router.get('/seller/payout-account',ah(async(req,res)=>ok(res,await safeOne('SELECT * FROM seller_payout_accounts WHERE user_id=:id OR restaurant_id IN (SELECT id FROM restaurants WHERE owner_id=:id) LIMIT 1',{id:req.user.id})))); router.put('/seller/payout-account',(req,res)=>ok(res,req.body,'Payout account saved'));
router.get('/delivery/dashboard',(req,res)=>ok(res,{activeOrders:0,totalDeliveries:0,cashDue:0}));
router.get('/delivery/profile',(req,res)=>ok(res,{user:req.user,online:true,verificationStatus:'PENDING'}));
router.post('/delivery/profile/status',(req,res)=>ok(res,{online:req.body.online??req.body.isOnline??true},'Status updated'));
router.post(['/delivery/location','/delivery/orders/:id/location'],ah(async(req,res)=>{await exec('INSERT INTO delivery_locations(order_id,driver_id,latitude,longitude,heading,created_at) VALUES(:oid,:did,:lat,:lng,:heading,NOW())',{oid:req.params.id||req.body.orderId||null,did:req.user.id,lat:req.body.latitude||req.body.lat,lng:req.body.longitude||req.body.lng,heading:req.body.heading||null}); ok(res,{saved:true});}));
router.get(['/delivery/offers/active','/delivery/orders/available'],ah(async(req,res)=>ok(res,await safeMany('SELECT *, grand_total total FROM orders WHERE status IN ("READY","READY_FOR_PICKUP","ACCEPTED","PLACED") AND id NOT IN (SELECT order_id FROM delivery_assignments WHERE status NOT IN ("CANCELLED","REJECTED")) LIMIT 20'))));
router.get('/delivery/orders',ah(async(req,res)=>ok(res,await safeMany('SELECT o.*, o.grand_total total FROM orders o JOIN delivery_assignments da ON da.order_id=o.id WHERE da.driver_id=:id ORDER BY o.id DESC LIMIT 100',{id:req.user.id}))));
router.get('/delivery/orders/:id',ah(async(req,res)=>ok(res,await orderDetail(req.params.id))));
router.post(['/delivery/orders/:id/accept','/delivery/offers/:id/accept'],ah(async(req,res)=>{await exec('INSERT INTO delivery_assignments(order_id,driver_id,status,accepted_at,created_at) VALUES(:oid,:did,"ACCEPTED",NOW(),NOW()) ON DUPLICATE KEY UPDATE driver_id=:did,status="ACCEPTED",accepted_at=NOW()',{oid:req.params.id,did:req.user.id}); await exec('UPDATE orders SET status="DRIVER_ASSIGNED" WHERE id=:id',{id:req.params.id}); ok(res,await orderDetail(req.params.id),'Order accepted');}));
router.post('/delivery/offers/:id/reject',(req,res)=>ok(res,null,'Offer rejected'));
router.get('/delivery/orders/current',ah(async(req,res)=>ok(res,await safeOne('SELECT o.*,o.grand_total total FROM orders o JOIN delivery_assignments da ON da.order_id=o.id WHERE da.driver_id=:id AND o.status NOT IN ("DELIVERED","CANCELLED") ORDER BY o.id DESC LIMIT 1',{id:req.user.id}))));
router.get('/delivery/orders/history',ah(async(req,res)=>ok(res,await safeMany('SELECT o.*,o.grand_total total FROM orders o JOIN delivery_assignments da ON da.order_id=o.id WHERE da.driver_id=:id ORDER BY o.id DESC LIMIT 100',{id:req.user.id}))));
for (const [p,s] of [['picked-up','PICKED_UP'],['pickup','PICKED_UP'],['out-for-delivery','OUT_FOR_DELIVERY'],['reached-drop','REACHED_DROP'],['cash-collected','CASH_COLLECTED'],['delivered','DELIVERED']]) router.post(`/delivery/orders/:id/${p}`,ah(async(req,res)=>{await exec('UPDATE orders SET status=:s, updated_at=NOW() WHERE id=:id',{s,id:req.params.id}); await exec('UPDATE delivery_assignments SET status=:s, updated_at=NOW() WHERE order_id=:id',{s,id:req.params.id}).catch(()=>{}); ok(res,await orderDetail(req.params.id),`Order ${s}`);}));
router.get('/delivery/cash/transactions',ah(async(req,res)=>ok(res,await safeMany('SELECT * FROM delivery_cash_transactions WHERE driver_id=:id ORDER BY id DESC LIMIT 100',{id:req.user.id})))); router.post('/delivery/cash/deposit',(req,res)=>ok(res,{status:'PENDING'},'Deposit submitted')); router.get('/delivery/cash/summary',(req,res)=>ok(res,{cashInHand:0,depositPending:0}));
router.get('/rider/verification/status',(req,res)=>ok(res,{status:'PENDING'})); router.post(['/rider/verification','/rider/verification/:id'],(req,res)=>ok(res,{status:'PENDING'},'Verification submitted'));
router.get('/user/orders/:id/tracking',ah(async(req,res)=>ok(res,{order:await orderDetail(req.params.id),locations:await safeMany('SELECT * FROM delivery_locations WHERE order_id=:id ORDER BY id DESC LIMIT 20',{id:req.params.id})})));
module.exports=router;
