const router = require('express').Router();
const { ok, fail } = require('../utils/respond');
const ah = require('../utils/asyncHandler');
const { optionalAuth } = require('../middleware/auth');
const { pool } = require('../utils/db');

router.use(optionalAuth);
async function x(sql, params = []) { const [r] = await pool.execute(sql, params); return r; }
async function q(sql, params = []) { try { const [r] = await pool.execute(sql, params); return r; } catch (e) { console.error('[singleBrandV43]', e.message, sql); return []; } }
async function one(sql, params = []) { const rows = await q(sql, params); return rows[0] || null; }
function n(v, d = 0) { const z = Number(v); return Number.isFinite(z) ? z : d; }
function b(v, d = true) { if (v == null) return d; if (Buffer.isBuffer(v)) return v[0] === 1; if (typeof v === 'boolean') return v; if (typeof v === 'number') return v === 1; return ['1','true','yes','open','active','available'].includes(String(v).toLowerCase()); }
function slug(v='') { return String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'') || 'category'; }
function rad(v) { return v * Math.PI / 180; }
function km(aLat, aLng, bLat, bLng) { const R=6371; const dLat=rad(bLat-aLat); const dLng=rad(bLng-aLng); const A=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLng/2)**2; return R*2*Math.atan2(Math.sqrt(A),Math.sqrt(1-A)); }
async function hasTable(t) { return !!await one('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[t]); }
async function cols(t) { const rows=await q('SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[t]); return new Set(rows.map(r=>r.COLUMN_NAME)); }
function pickCol(set, names, fallback='NULL') { for (const z of names) if (set.has(z)) return z; return fallback; }
async function addCol(table,col,sql) { const c=await cols(table); if(!c.has(col)) { try { await x(`ALTER TABLE ${table} ADD COLUMN ${sql}`); } catch(e) { console.error('[v43 addCol]',table,col,e.message); } } }
async function ensureSchema() {
  await x(`CREATE TABLE IF NOT EXISTS outlets (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    legacy_restaurant_id BIGINT NULL,
    outlet_code VARCHAR(80) UNIQUE,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(220) NULL,
    address VARCHAR(700), city VARCHAR(120), state VARCHAR(120), pincode VARCHAR(20),
    latitude DECIMAL(12,8), longitude DECIMAL(12,8), service_radius_km DECIMAL(8,2) DEFAULT 5,
    contact_phone VARCHAR(40), contact_email VARCHAR(255), whatsapp_number VARCHAR(40), google_map_link VARCHAR(700),
    manager_user_id BIGINT NULL, manager_name VARCHAR(255), manager_phone VARCHAR(40), manager_email VARCHAR(255),
    opening_time VARCHAR(20), closing_time VARCHAR(20), seating_available BIT(1) NOT NULL DEFAULT b'0', booking_enabled BIT(1) NOT NULL DEFAULT b'1',
    is_open BIT(1) NOT NULL DEFAULT b'1', is_active BIT(1) NOT NULL DEFAULT b'1', takeaway_enabled BIT(1) NOT NULL DEFAULT b'1', delivery_enabled BIT(1) NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_outlets_geo_v43 (latitude, longitude), INDEX idx_outlets_city_v43 (city,pincode)
  )`);
  await addCol('outlets','slug','slug VARCHAR(220) NULL');
  await addCol('outlets','legacy_restaurant_id','legacy_restaurant_id BIGINT NULL');
  await addCol('outlets','latitude','latitude DECIMAL(12,8) NULL');
  await addCol('outlets','longitude','longitude DECIMAL(12,8) NULL');
  await addCol('outlets','service_radius_km','service_radius_km DECIMAL(8,2) DEFAULT 5');
  await addCol('outlets','contact_phone','contact_phone VARCHAR(40) NULL');
  await addCol('outlets','contact_email','contact_email VARCHAR(255) NULL');
  await addCol('outlets','whatsapp_number','whatsapp_number VARCHAR(40) NULL');
  await addCol('outlets','google_map_link','google_map_link VARCHAR(700) NULL');
  await addCol('outlets','manager_name','manager_name VARCHAR(255) NULL');
  await addCol('outlets','manager_phone','manager_phone VARCHAR(40) NULL');
  await addCol('outlets','manager_email','manager_email VARCHAR(255) NULL');
  await addCol('outlets','opening_time','opening_time VARCHAR(20) NULL');
  await addCol('outlets','closing_time','closing_time VARCHAR(20) NULL');
  await addCol('outlets','booking_enabled',"booking_enabled BIT(1) NOT NULL DEFAULT b'1'");
  await addCol('outlets','seating_available',"seating_available BIT(1) NOT NULL DEFAULT b'0'");
  await addCol('outlets','takeaway_enabled',"takeaway_enabled BIT(1) NOT NULL DEFAULT b'1'");
  await addCol('outlets','delivery_enabled',"delivery_enabled BIT(1) NOT NULL DEFAULT b'1'");
  await x(`CREATE TABLE IF NOT EXISTS outlet_product_stock (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, outlet_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
    opening_stock INT NOT NULL DEFAULT 0, stock_quantity INT NOT NULL DEFAULT 0, reserved_quantity INT NOT NULL DEFAULT 0,
    low_stock_alert INT NOT NULL DEFAULT 5, is_available BIT(1) NOT NULL DEFAULT b'1', preparation_minutes INT DEFAULT 15,
    unit_cost DECIMAL(12,2) DEFAULT 0, selling_price DECIMAL(12,2) DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_outlet_product_stock_v43 (outlet_id, product_id), INDEX idx_ops_outlet_v43 (outlet_id)
  )`);
  await x(`CREATE TABLE IF NOT EXISTS outlet_stock_movements (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, outlet_id BIGINT NOT NULL, product_id BIGINT NOT NULL, movement_type VARCHAR(40) NOT NULL,
    quantity INT NOT NULL DEFAULT 0, before_stock INT NOT NULL DEFAULT 0, after_stock INT NOT NULL DEFAULT 0,
    unit_cost DECIMAL(12,2) DEFAULT 0, total_cost DECIMAL(12,2) DEFAULT 0, note VARCHAR(700), created_by VARCHAR(120),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_osm_outlet_date_v43 (outlet_id, created_at)
  )`);
  await x(`CREATE TABLE IF NOT EXISTS outlet_daily_closings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, outlet_id BIGINT NOT NULL, closing_date DATE NOT NULL,
    online_sales DECIMAL(12,2) NOT NULL DEFAULT 0, offline_sales DECIMAL(12,2) NOT NULL DEFAULT 0, cod_sales DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_sales DECIMAL(12,2) NOT NULL DEFAULT 0, order_count INT NOT NULL DEFAULT 0, offline_order_count INT NOT NULL DEFAULT 0,
    cash_in_hand DECIMAL(12,2) NOT NULL DEFAULT 0, expenses DECIMAL(12,2) NOT NULL DEFAULT 0, net_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
    closing_note VARCHAR(1000), closed_by VARCHAR(120), submitted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_outlet_daily_v43 (outlet_id, closing_date), INDEX idx_odc_date_v43 (closing_date)
  )`);
  await x(`CREATE TABLE IF NOT EXISTS outlet_bookings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, outlet_id BIGINT NOT NULL, customer_id BIGINT NULL, customer_name VARCHAR(255), phone VARCHAR(40), email VARCHAR(255),
    booking_type VARCHAR(80) DEFAULT 'GENERAL', booking_date DATE NULL, booking_time VARCHAR(40), people_count INT DEFAULT 1, note VARCHAR(1000), status VARCHAR(40) DEFAULT 'PENDING',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_ob_outlet_v43 (outlet_id, created_at)
  )`);
  await x(`CREATE TABLE IF NOT EXISTS outlet_delivery_boys (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, outlet_id BIGINT NOT NULL, user_id BIGINT NOT NULL, is_active BIT(1) NOT NULL DEFAULT b'1',
    assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_odb_user_v43 (user_id), INDEX idx_odb_outlet_v43 (outlet_id)
  )`);
  await x(`CREATE TABLE IF NOT EXISTS food_categories (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(160) NULL,
    title VARCHAR(160) NULL,
    slug VARCHAR(200) NULL,
    description TEXT NULL,
    image_url TEXT NULL,
    image TEXT NULL,
    icon TEXT NULL,
    enabled BIT(1) NOT NULL DEFAULT b'1',
    active BIT(1) NOT NULL DEFAULT b'1',
    deleted BIT(1) NOT NULL DEFAULT b'0',
    show_on_home BIT(1) NOT NULL DEFAULT b'1',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
  )`);
  await seedOutletsFromRestaurantsIfNeeded();
}
async function seedOutletsFromRestaurantsIfNeeded() {
  const existing = await one('SELECT COUNT(*) c FROM outlets');
  if (n(existing?.c) > 0) return;
  if (!await hasTable('restaurants')) return;
  const c=await cols('restaurants');
  const id=pickCol(c,['id']); const name=pickCol(c,['name','restaurant_name','title'],"'Mr Breado'"); const address=pickCol(c,['address','street','location'],"''"); const city=pickCol(c,['city'],"''"); const state=pickCol(c,['state'],"''"); const pincode=pickCol(c,['pincode','pin_code','zip'],"''"); const lat=pickCol(c,['latitude','lat'],'NULL'); const lng=pickCol(c,['longitude','lng','lon'],'NULL'); const phone=pickCol(c,['phone','mobile','contact_phone','owner_phone'],"''"); const email=pickCol(c,['email','contact_email'],"''"); const open=pickCol(c,['is_open','open'],'1');
  const rows=await q(`SELECT ${id} id, ${name} name, ${address} address, ${city} city, ${state} state, ${pincode} pincode, ${lat} latitude, ${lng} longitude, ${phone} phone, ${email} email, ${open} is_open FROM restaurants ORDER BY ${id} LIMIT 100`);
  for (const r of rows) await x(`INSERT IGNORE INTO outlets (legacy_restaurant_id,outlet_code,name,slug,address,city,state,pincode,latitude,longitude,contact_phone,contact_email,is_open,is_active,service_radius_km) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,5)`,[r.id,`MRB-${r.id}`,r.name||'Mr Breado',slug(`${r.name||'mr-breado'}-${r.id}`),r.address||'',r.city||'',r.state||'',r.pincode||'',r.latitude||null,r.longitude||null,r.phone||'',r.email||'',b(r.is_open)?1:0]);
}
function mapOutlet(r) { return { id:n(r.id), outletId:n(r.id), outletCode:r.outlet_code, outletName:r.name, name:r.name, slug:r.slug || slug(`${r.name}-${r.id}`), address:r.address||'', city:r.city||'', state:r.state||'', pincode:r.pincode||'', latitude:r.latitude==null?null:Number(r.latitude), longitude:r.longitude==null?null:Number(r.longitude), serviceRadiusKm:n(r.service_radius_km,5), contactPhone:r.contact_phone, contactEmail:r.contact_email, whatsappNumber:r.whatsapp_number, googleMapLink:r.google_map_link, managerName:r.manager_name, managerPhone:r.manager_phone, managerEmail:r.manager_email, openingTime:r.opening_time, closingTime:r.closing_time, isOpen:b(r.is_open), isActive:b(r.is_active), bookingEnabled:b(r.booking_enabled), deliveryEnabled:b(r.delivery_enabled), takeawayEnabled:b(r.takeaway_enabled) }; }
async function outletsList() { await ensureSchema(); return (await q('SELECT * FROM outlets WHERE COALESCE(is_active,1)=1 ORDER BY id DESC')).map(mapOutlet); }
async function outletById(id) { await ensureSchema(); const r=await one('SELECT * FROM outlets WHERE id=?',[id]); return r?mapOutlet(r):null; }
async function ordersAgg(outletId, from='1970-01-01', to='2999-12-31') { if(!await hasTable('orders')) return { totalSales:0, onlineSales:0, codSales:0, orders:0, averageOrderValue:0 }; const c=await cols('orders'); const outCol=pickCol(c,['outlet_id','restaurant_id'],'NULL'); const total=pickCol(c,['grand_total','total_amount','total','payable_amount','amount','final_amount'],'0'); const pay=pickCol(c,['payment_method','payment_type'],'NULL'); const created=pickCol(c,['created_at','order_date','placed_at'],'NOW()'); if(outCol==='NULL') return {totalSales:0,onlineSales:0,codSales:0,orders:0,averageOrderValue:0}; const r=await one(`SELECT COUNT(*) orders, COALESCE(SUM(${total}),0) totalSales, COALESCE(SUM(CASE WHEN UPPER(COALESCE(${pay},'')) LIKE '%COD%' THEN ${total} ELSE 0 END),0) codSales, COALESCE(SUM(CASE WHEN UPPER(COALESCE(${pay},'')) NOT LIKE '%COD%' THEN ${total} ELSE 0 END),0) onlineSales FROM orders WHERE ${outCol}=? AND DATE(${created}) BETWEEN ? AND ?`,[outletId,from,to]); return { orders:n(r?.orders), totalSales:n(r?.totalSales), onlineSales:n(r?.onlineSales), codSales:n(r?.codSales), averageOrderValue:n(r?.orders)>0?n(r?.totalSales)/n(r?.orders):0 }; }
async function stockForOutlet(outletId) { await ensureSchema(); if(!await hasTable('products')) return []; const pc=await cols('products'); const name=pickCol(pc,['name','title','product_name'],"'Food'"); const img=pickCol(pc,['image_url','image','thumbnail_url'],'NULL'); const price=pickCol(pc,['price','discount_price','selling_price'],'0'); const deleted=pc.has('deleted')?'COALESCE(p.deleted,0)=0':'1=1'; const available=pc.has('available')?'COALESCE(p.available,1)=1':'1=1'; return await q(`SELECT ops.*, p.${name} productName, p.${img} imageUrl, p.${price} price FROM outlet_product_stock ops JOIN products p ON p.id=ops.product_id WHERE ops.outlet_id=? AND ${deleted} AND ${available} ORDER BY p.${name}`,[outletId]); }
async function bestFoods(outletId, from='1970-01-01', to='2999-12-31', slow=false) { if(!await hasTable('order_items') || !await hasTable('orders') || !await hasTable('products')) return []; const oc=await cols('orders'), ic=await cols('order_items'), pc=await cols('products'); const outCol=pickCol(oc,['outlet_id','restaurant_id'],'NULL'); const oid=pickCol(ic,['order_id']); const pid=pickCol(ic,['product_id','food_id']); const qty=pickCol(ic,['quantity','qty'],'1'); const total=pickCol(ic,['total_price','line_total','price'],'0'); const created=pickCol(oc,['created_at','order_date','placed_at'],'NOW()'); const name=pickCol(pc,['name','title','product_name'],"'Food'"); if(outCol==='NULL') return []; return await q(`SELECT p.id productId, p.${name} productName, COALESCE(SUM(oi.${qty}),0) soldQuantity, COALESCE(SUM(oi.${total}),0) grossSales FROM order_items oi JOIN orders o ON o.id=oi.${oid} JOIN products p ON p.id=oi.${pid} WHERE o.${outCol}=? AND DATE(o.${created}) BETWEEN ? AND ? GROUP BY p.id,p.${name} ORDER BY soldQuantity ${slow?'ASC':'DESC'} LIMIT 10`,[outletId,from,to]); }
async function dashboard(outletId, from='1970-01-01', to='2999-12-31') { const outlet=await outletById(outletId); if(!outlet) return null; const oa=await ordersAgg(outletId,from,to); const closing=await q('SELECT * FROM outlet_daily_closings WHERE outlet_id=? AND closing_date BETWEEN ? AND ? ORDER BY closing_date DESC',[outletId,from,to]); const offline=closing.reduce((a,r)=>a+n(r.offline_sales),0); const codClosing=closing.reduce((a,r)=>a+n(r.cod_sales),0); const stock=await stockForOutlet(outletId); const movements=await q('SELECT osm.*, p.name productName FROM outlet_stock_movements osm LEFT JOIN products p ON p.id=osm.product_id WHERE osm.outlet_id=? ORDER BY osm.created_at DESC LIMIT 200',[outletId]); const bookings=await q('SELECT * FROM outlet_bookings WHERE outlet_id=? ORDER BY created_at DESC LIMIT 100',[outletId]); return { outlet, summary:{ totalSales:n(oa.totalSales)+offline, onlineSales:oa.onlineSales, codSales:n(oa.codSales)+codClosing, offlineSales:offline, orders:oa.orders, averageOrderValue:oa.averageOrderValue, stockItems:stock.length, lowStock:stock.filter(s=>n(s.stock_quantity)<=n(s.low_stock_alert,5)).length, bookings:bookings.length }, stock, stockMovements:movements, closingCalendar:closing, bookings, bestFoods:await bestFoods(outletId,from,to,false), slowFoods:await bestFoods(outletId,from,to,true) }; }
async function menuForOutlet(outletId) { await ensureSchema(); if(!await hasTable('products')) return []; const pc=await cols('products'); const name=pickCol(pc,['name','title','product_name'],"'Food'"); const img=pickCol(pc,['image_url','image','thumbnail_url'],'NULL'); const price=pickCol(pc,['price','discount_price','selling_price'],'0'); const cat=pickCol(pc,['food_category_id','category_id'],'NULL'); const deleted=pc.has('deleted')?'COALESCE(p.deleted,0)=0':'1=1'; const available=pc.has('available')?'COALESCE(p.available,1)=1':'1=1'; const rows=await q(`SELECT p.*, p.${name} name, p.${img} imageUrl, p.${price} price, p.${cat} categoryId, ops.stock_quantity stock, ops.is_available outletAvailable, ops.preparation_minutes preparationMinutes, ops.selling_price outletPrice FROM products p LEFT JOIN outlet_product_stock ops ON ops.product_id=p.id AND ops.outlet_id=? WHERE ${deleted} AND ${available} AND COALESCE(ops.is_available,1)=1 ORDER BY p.id DESC`,[outletId]); return rows.map(r=>({ ...r, productId:r.id, name:r.name, imageUrl:r.imageUrl, price:n(r.outletPrice || r.price), stock:n(r.stock), available:n(r.stock)>0 || r.stock == null })); }
async function nearest(lat,lng) { const la=n(lat,NaN), lo=n(lng,NaN); if(!Number.isFinite(la)||!Number.isFinite(lo)) return null; const outlets=await outletsList(); const ranked=outlets.filter(o=>o.latitude!=null&&o.longitude!=null).map(o=>{const d=km(la,lo,Number(o.latitude),Number(o.longitude)); return {...o,distanceKm:Number(d.toFixed(2)),isServiceable:d<=n(o.serviceRadiusKm,5)};}).sort((a,b)=>a.distanceKm-b.distanceKm); return ranked[0] || null; }
function mapCat(r){ return { id:n(r.id), name:r.name||r.title, title:r.title||r.name, slug:r.slug||slug(r.name||r.title), imageUrl:r.image_url||r.image||r.icon||'', image:r.image_url||r.image||r.icon||'', active:b(r.enabled)&&b(r.active), sortOrder:n(r.sort_order) }; }
async function categories(){ await ensureSchema(); return (await q(`SELECT * FROM food_categories WHERE COALESCE(deleted,0)=0 AND COALESCE(enabled,1)=1 AND COALESCE(active,1)=1 ORDER BY COALESCE(sort_order,0), id`)).map(mapCat); }

router.get('/single-brand/v43/version', (req,res)=>ok(res,{version:'single-brand-enterprise-v43',fixes:['outlet full dashboard route','admin/user outlet loaded categories','single-brand outlet menu'],razorpay:'v22/v26 locked unchanged'}));
router.post('/admin/outlets/ensure-enterprise-v43-schema', ah(async(req,res)=>{ await ensureSchema(); ok(res,{ready:true,version:'v43'},'Enterprise outlet schema ready'); }));
router.get(['/admin/outlets','/outlets','/user/outlets'], ah(async(req,res)=>ok(res,await outletsList(),'Outlets loaded')));
router.get('/admin/business/dashboard', ah(async(req,res)=>{ const from=req.query.from||'1970-01-01', to=req.query.to||'2999-12-31'; const outs=await outletsList(); const enriched=[]; for(const o of outs){ const d=await dashboard(o.id,from,to); enriched.push({...o,totalSales:n(d?.summary?.totalSales),onlineSales:n(d?.summary?.onlineSales),codSales:n(d?.summary?.codSales),offlineSales:n(d?.summary?.offlineSales),orderCount:n(d?.summary?.orders),lowStockCount:n(d?.summary?.lowStock),productCount:n(d?.summary?.stockItems),topFoods:d?.bestFoods||[],slowFoods:d?.slowFoods||[]}); } ok(res,{from,to,totalOutlets:enriched.length,totalSales:enriched.reduce((a,o)=>a+n(o.totalSales),0),onlineSales:enriched.reduce((a,o)=>a+n(o.onlineSales),0),codSales:enriched.reduce((a,o)=>a+n(o.codSales),0),offlineSales:enriched.reduce((a,o)=>a+n(o.offlineSales),0),totalOrders:enriched.reduce((a,o)=>a+n(o.orderCount),0),orders:enriched.reduce((a,o)=>a+n(o.orderCount),0),outlets:enriched},'Head office business dashboard loaded'); }));
router.post('/admin/outlets', ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; const name=body.name||body.outletName||'Mr Breado Outlet'; const code=body.outletCode||body.outlet_code||`MRB-${Date.now().toString().slice(-6)}`; await x(`INSERT INTO outlets (outlet_code,name,slug,address,city,state,pincode,latitude,longitude,service_radius_km,contact_phone,contact_email,whatsapp_number,google_map_link,manager_name,manager_phone,manager_email,opening_time,closing_time,is_open,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,1)`,[code,name,slug(`${name}-${code}`),body.address||'',body.city||'',body.state||'',body.pincode||'',body.latitude||null,body.longitude||null,n(body.serviceRadiusKm||body.service_radius_km,5),body.contactPhone||body.phone||'',body.contactEmail||body.email||'',body.whatsappNumber||'',body.googleMapLink||'',body.managerName||'',body.managerPhone||'',body.managerEmail||'',body.openingTime||'',body.closingTime||'']); ok(res,mapOutlet(await one('SELECT * FROM outlets WHERE outlet_code=?',[code])),'Outlet created',201); }));
router.put('/admin/outlets/:id', ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; await x(`UPDATE outlets SET name=COALESCE(?,name), slug=COALESCE(?,slug), address=COALESCE(?,address), city=COALESCE(?,city), state=COALESCE(?,state), pincode=COALESCE(?,pincode), latitude=COALESCE(?,latitude), longitude=COALESCE(?,longitude), service_radius_km=COALESCE(?,service_radius_km), contact_phone=COALESCE(?,contact_phone), contact_email=COALESCE(?,contact_email), whatsapp_number=COALESCE(?,whatsapp_number), google_map_link=COALESCE(?,google_map_link), manager_name=COALESCE(?,manager_name), manager_phone=COALESCE(?,manager_phone), manager_email=COALESCE(?,manager_email), opening_time=COALESCE(?,opening_time), closing_time=COALESCE(?,closing_time), is_open=COALESCE(?,is_open) WHERE id=?`,[body.name||body.outletName||null,body.slug||null,body.address||null,body.city||null,body.state||null,body.pincode||null,body.latitude??null,body.longitude??null,body.serviceRadiusKm??body.service_radius_km??null,body.contactPhone||body.phone||null,body.contactEmail||body.email||null,body.whatsappNumber||null,body.googleMapLink||null,body.managerName||null,body.managerPhone||null,body.managerEmail||null,body.openingTime||null,body.closingTime||null,body.isOpen===undefined?null:(body.isOpen?1:0),req.params.id]); ok(res,await outletById(req.params.id),'Outlet updated'); }));
router.post(['/admin/outlets/:id/location','/admin/outlets/:id/set-location'], ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; if(body.latitude==null||body.longitude==null) return fail(res,'latitude and longitude required',400); await x('UPDATE outlets SET latitude=?, longitude=?, service_radius_km=COALESCE(?,service_radius_km), address=COALESCE(?,address), google_map_link=COALESCE(?,google_map_link) WHERE id=?',[body.latitude,body.longitude,body.serviceRadiusKm??body.service_radius_km??null,body.address||null,body.googleMapLink||null,req.params.id]); ok(res,await outletById(req.params.id),'Outlet location updated'); }));
router.get(['/admin/outlets/:id/full-dashboard','/admin/business/outlets/:id/dashboard','/admin/outlets/:id/business-dashboard','/admin/outlets/:id/performance'], ah(async(req,res)=>{ const data=await dashboard(req.params.id,req.query.from||'1970-01-01',req.query.to||'2999-12-31'); if(!data) return fail(res,'Outlet not found',404); ok(res,data,'Outlet full business dashboard loaded'); }));
router.post(['/admin/outlets/:id/stock','/outlet-manager/stock'], ah(async(req,res)=>{ await ensureSchema(); const outletId=n(req.params.id||req.body?.outletId); const items=Array.isArray(req.body?.items)?req.body.items:[req.body]; const out=[]; for(const item of items){ const productId=n(item.productId||item.product_id); if(!productId) continue; const existing=await one('SELECT * FROM outlet_product_stock WHERE outlet_id=? AND product_id=?',[outletId,productId]); const before=n(existing?.stock_quantity); const stock=n(item.stockQuantity ?? item.stock_quantity ?? (before+n(item.quantity,0))); const unitCost=n(item.unitCost||item.unit_cost); await x(`INSERT INTO outlet_product_stock (outlet_id,product_id,opening_stock,stock_quantity,low_stock_alert,is_available,preparation_minutes,unit_cost,selling_price) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE stock_quantity=VALUES(stock_quantity),low_stock_alert=VALUES(low_stock_alert),is_available=VALUES(is_available),preparation_minutes=VALUES(preparation_minutes),unit_cost=VALUES(unit_cost),selling_price=VALUES(selling_price)`,[outletId,productId,before,stock,n(item.lowStockAlert||item.low_stock_alert,5),item.isAvailable===false?0:1,n(item.preparationMinutes||item.preparation_minutes,15),unitCost,n(item.sellingPrice||item.selling_price)]); await x('INSERT INTO outlet_stock_movements (outlet_id,product_id,movement_type,quantity,before_stock,after_stock,unit_cost,total_cost,note,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)',[outletId,productId,item.movementType||'MANUAL_UPDATE',stock-before,before,stock,unitCost,unitCost*(stock-before),item.note||'',req.user?.username||'admin']); out.push({productId,beforeStock:before,afterStock:stock}); } ok(res,{outletId,updated:out},'Outlet stock updated'); }));
router.get(['/outlets/nearest','/user/outlets/nearest'], ah(async(req,res)=>{ const o=await nearest(req.query.lat??req.query.latitude,req.query.lng??req.query.longitude); if(!o) return fail(res,'No Mr Breado outlet found. Set outlet latitude/longitude in admin.',404); ok(res,o,o.isServiceable?'Nearest outlet found':'Nearest outlet found but outside service radius'); }));
router.get(['/menu/nearest','/user/menu/nearest'], ah(async(req,res)=>{ const o=await nearest(req.query.lat??req.query.latitude,req.query.lng??req.query.longitude); if(!o) return fail(res,'No Mr Breado outlet found. Set outlet latitude/longitude in admin.',404); const menu=await menuForOutlet(o.id); ok(res,{outlet:o,menu,foods:menu,products:menu},'Nearest outlet menu loaded'); }));
router.get(['/outlets/:id/menu','/user/outlets/:id/menu'], ah(async(req,res)=>{ const outlet=await outletById(req.params.id); if(!outlet) return fail(res,'Outlet not found',404); const menu=await menuForOutlet(outlet.id); ok(res,{outlet,menu,foods:menu,products:menu},'Outlet menu loaded'); }));
router.get(['/outlets/:id/contact','/user/outlets/:id/contact'], ah(async(req,res)=>{ const outlet=await outletById(req.params.id); if(!outlet) return fail(res,'Outlet not found',404); ok(res,{outletId:outlet.id,name:outlet.name,address:outlet.address,phone:outlet.contactPhone||outlet.managerPhone,email:outlet.contactEmail||outlet.managerEmail,whatsapp:outlet.whatsappNumber,googleMapLink:outlet.googleMapLink,openingTime:outlet.openingTime,closingTime:outlet.closingTime,bookingEnabled:outlet.bookingEnabled},'Outlet contact loaded'); }));
router.post(['/outlets/:id/bookings','/user/outlets/:id/bookings'], ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; await x('INSERT INTO outlet_bookings (outlet_id,customer_id,customer_name,phone,email,booking_type,booking_date,booking_time,people_count,note,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[req.params.id,req.user?.id||body.customerId||null,body.customerName||body.name||'',body.phone||'',body.email||'',body.bookingType||'GENERAL',body.bookingDate||body.date||null,body.bookingTime||body.time||'',n(body.peopleCount||body.people_count,1),body.note||body.message||'','PENDING']); ok(res,{outletId:req.params.id},'Booking request submitted',201); }));
router.get(['/categories','/user/categories','/food-categories'], ah(async(req,res)=>ok(res,await categories(),'Categories loaded')));
router.get('/admin/categories', ah(async(req,res)=>ok(res,await categories(),'Admin categories loaded')));
router.post(['/admin/categories','/admin/food-categories'], ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; const name=body.name||body.title; if(!name) return fail(res,'Category name required',400); const s=body.slug||slug(name); const image=body.imageUrl||body.image_url||body.image||body.icon||''; const r=await x('INSERT INTO food_categories (name,title,slug,description,image_url,image,icon,enabled,active,show_on_home,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[name,name,s,body.description||'',image,image,image,body.active===false?0:1,body.active===false?0:1,body.showOnHome===false?0:1,n(body.sortOrder||body.sort_order)]); ok(res,mapCat(await one('SELECT * FROM food_categories WHERE id=?',[r.insertId])),'Category created',201); }));
router.put(['/admin/categories/:id','/admin/food-categories/:id'], ah(async(req,res)=>{ await ensureSchema(); const body=req.body||{}; const name=body.name||body.title||null; const image=body.imageUrl||body.image_url||body.image||body.icon||null; await x('UPDATE food_categories SET name=COALESCE(?,name), title=COALESCE(?,title), slug=COALESCE(?,slug), description=COALESCE(?,description), image_url=COALESCE(?,image_url), image=COALESCE(?,image), icon=COALESCE(?,icon), sort_order=COALESCE(?,sort_order), updated_at=NOW(6) WHERE id=?',[name,name,body.slug||null,body.description||null,image,image,image,body.sortOrder??body.sort_order??null,req.params.id]); ok(res,mapCat(await one('SELECT * FROM food_categories WHERE id=?',[req.params.id])),'Category updated'); }));
router.patch(['/admin/categories/:id/status','/admin/food-categories/:id/status'], ah(async(req,res)=>{ const active=req.body?.active??req.body?.enabled??true; await x('UPDATE food_categories SET enabled=?, active=? WHERE id=?',[active?1:0,active?1:0,req.params.id]); ok(res,mapCat(await one('SELECT * FROM food_categories WHERE id=?',[req.params.id])),'Category status updated'); }));
router.delete(['/admin/categories/:id','/admin/food-categories/:id'], ah(async(req,res)=>{ await x('UPDATE food_categories SET deleted=1, enabled=0, active=0 WHERE id=?',[req.params.id]); ok(res,{id:req.params.id},'Category deleted'); }));
router.get('/admin/reports/outlet-accounting.csv', ah(async(req,res)=>{ await ensureSchema(); const from=req.query.from||'1970-01-01', to=req.query.to||'2999-12-31', outletId=req.query.outletId||null; const params=outletId?[outletId,from,to]:[from,to]; const where=outletId?'WHERE odc.outlet_id=? AND closing_date BETWEEN ? AND ?':'WHERE closing_date BETWEEN ? AND ?'; const rows=await q(`SELECT o.name outletName, odc.* FROM outlet_daily_closings odc JOIN outlets o ON o.id=odc.outlet_id ${where} ORDER BY closing_date DESC`,params); const csv=['Outlet,Date,Online Sales,COD Sales,Offline Sales,Total Sales,Orders,Offline Orders,Cash In Hand,Expenses,Net Cash,Note',...rows.map(r=>`"${String(r.outletName||'').replace(/"/g,'""')}",${String(r.closing_date).slice(0,10)},${r.online_sales},${r.cod_sales},${r.offline_sales},${r.total_sales},${r.order_count},${r.offline_order_count},${r.cash_in_hand},${r.expenses},${r.net_cash},"${String(r.closing_note||'').replace(/"/g,'""')}"`)].join('\n'); res.setHeader('Content-Type','text/csv'); res.setHeader('Content-Disposition','attachment; filename="mr_breado_outlet_accounting_v43.csv"'); res.send(csv); }));
module.exports = router;
