
const express = require('express');
const router = express.Router();
const ah = require('../utils/asyncHandler');
const { ok } = require('../utils/respond');
const { one, many, exec, slugify } = require('../utils/db');

async function tryExec(sql, params={}) { try { return await exec(sql, params); } catch (e) { return null; } }
async function tryMany(sql, params={}) { try { return await many(sql, params); } catch (e) { return []; } }
async function tryOne(sql, params={}) { try { return await one(sql, params); } catch (e) { return null; } }
function n(v,d=0){ const x=Number(v); return Number.isFinite(x)?x:d; }
function s(v,d=''){ return v === undefined || v === null ? d : String(v); }
function bool(v,d=true){ if (v === undefined || v === null || v === '') return d; if (Buffer.isBuffer(v)) return v[0]===1; if (typeof v === 'boolean') return v; if (typeof v === 'number') return v!==0; const x=String(v).toLowerCase(); return !['0','false','no','inactive','disabled'].includes(x); }
function today(){ return new Date().toISOString().slice(0,10); }
function dateOrNull(v){ if(!v) return null; const d=new Date(v); return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0,10); }
function haversineKm(a,b,c,d){ const R=6371, toRad=x=>Number(x)*Math.PI/180; const dLat=toRad(c)-toRad(a), dLng=toRad(d)-toRad(b); const x=Math.sin(dLat/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(dLng/2)**2; return 2*R*Math.asin(Math.sqrt(x)); }
async function ensureV50Schema(){
  await tryExec(`CREATE TABLE IF NOT EXISTS outlets (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    outlet_code VARCHAR(80) UNIQUE,
    name VARCHAR(180) NOT NULL DEFAULT 'Mr Breado', slug VARCHAR(220),
    address TEXT, city VARCHAR(120), state VARCHAR(120), pincode VARCHAR(20),
    latitude DECIMAL(12,8) NULL, longitude DECIMAL(12,8) NULL,
    service_radius_km DECIMAL(10,2) NOT NULL DEFAULT 5.00,
    phone VARCHAR(30), email VARCHAR(180), manager_name VARCHAR(180), manager_phone VARCHAR(30), manager_email VARCHAR(180),
    banner_image LONGTEXT NULL, profile_image LONGTEXT NULL, logo_image LONGTEXT NULL,
    opening_time VARCHAR(20), closing_time VARCHAR(20), google_map_link TEXT,
    is_open TINYINT(1) NOT NULL DEFAULT 1, is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`);
  for (const col of ['banner_image LONGTEXT NULL','profile_image LONGTEXT NULL','logo_image LONGTEXT NULL','opening_time VARCHAR(20)','closing_time VARCHAR(20)','google_map_link TEXT','phone VARCHAR(30)','email VARCHAR(180)','manager_name VARCHAR(180)','manager_phone VARCHAR(30)','manager_email VARCHAR(180)','service_radius_km DECIMAL(10,2) NOT NULL DEFAULT 5.00','latitude DECIMAL(12,8) NULL','longitude DECIMAL(12,8) NULL','pincode VARCHAR(20)','city VARCHAR(120)','state VARCHAR(120)','is_open TINYINT(1) NOT NULL DEFAULT 1','is_active TINYINT(1) NOT NULL DEFAULT 1']) await tryExec(`ALTER TABLE outlets ADD COLUMN ${col}`);
  await tryExec(`CREATE TABLE IF NOT EXISTS outlet_product_stock (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    outlet_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
    stock_qty INT NOT NULL DEFAULT 0, min_stock_qty INT NOT NULL DEFAULT 5,
    prep_time_minutes INT NOT NULL DEFAULT 20, is_available TINYINT(1) NOT NULL DEFAULT 1,
    unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0, selling_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY outlet_product_unique(outlet_id, product_id)
  )`);
  for (const col of ['unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0','selling_price DECIMAL(12,2) NOT NULL DEFAULT 0','prep_time_minutes INT NOT NULL DEFAULT 20','min_stock_qty INT NOT NULL DEFAULT 5','is_available TINYINT(1) NOT NULL DEFAULT 1']) await tryExec(`ALTER TABLE outlet_product_stock ADD COLUMN ${col}`);
  await tryExec(`CREATE TABLE IF NOT EXISTS outlet_stock_movements (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    outlet_id BIGINT NOT NULL, product_id BIGINT NULL,
    movement_type VARCHAR(40) NOT NULL DEFAULT 'ADJUSTMENT', quantity INT NOT NULL DEFAULT 0,
    before_stock INT DEFAULT NULL, after_stock INT DEFAULT NULL,
    unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0, total_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    note TEXT, created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await tryExec(`CREATE TABLE IF NOT EXISTS outlet_daily_closings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    outlet_id BIGINT NOT NULL, closing_date DATE NOT NULL,
    online_sales DECIMAL(12,2) NOT NULL DEFAULT 0, cod_sales DECIMAL(12,2) NOT NULL DEFAULT 0, offline_sales DECIMAL(12,2) NOT NULL DEFAULT 0,
    expenses DECIMAL(12,2) NOT NULL DEFAULT 0, net_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
    note TEXT, closed_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY outlet_day_unique(outlet_id, closing_date)
  )`);
  await tryExec(`CREATE TABLE IF NOT EXISTS offers (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(220) NOT NULL, subtitle VARCHAR(220), description TEXT,
    image_url LONGTEXT, coupon_enabled TINYINT(1) NOT NULL DEFAULT 0,
    coupon_code VARCHAR(80), discount_type ENUM('FLAT','PERCENT','FREE_DELIVERY') NOT NULL DEFAULT 'PERCENT',
    discount_value DECIMAL(12,2) NOT NULL DEFAULT 0, min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0, max_discount DECIMAL(12,2) NOT NULL DEFAULT 0,
    valid_from DATE NULL, valid_to DATE NULL, enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`);
  for (const col of ['coupon_enabled TINYINT(1) NOT NULL DEFAULT 0','coupon_code VARCHAR(80)','discount_type ENUM(\'FLAT\',\'PERCENT\',\'FREE_DELIVERY\') NOT NULL DEFAULT \'PERCENT\'','discount_value DECIMAL(12,2) NOT NULL DEFAULT 0','min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0','max_discount DECIMAL(12,2) NOT NULL DEFAULT 0','valid_from DATE NULL','valid_to DATE NULL','enabled TINYINT(1) NOT NULL DEFAULT 1','image_url LONGTEXT']) await tryExec(`ALTER TABLE offers ADD COLUMN ${col}`);
  await tryExec(`CREATE TABLE IF NOT EXISTS coupon_rules (
    id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(80) UNIQUE NOT NULL, title VARCHAR(180), description TEXT,
    coupon_type ENUM('FLAT','PERCENT','FREE_DELIVERY') NOT NULL DEFAULT 'FLAT', discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0, max_discount DECIMAL(12,2) NOT NULL DEFAULT 0,
    start_date DATE NULL, end_date DATE NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`);
}
async function seedOutlets(){ await ensureV50Schema(); const c=(await tryOne(`SELECT COUNT(*) c FROM outlets`))?.c||0; if(c>0) return; const rs=await tryMany(`SELECT id,name,address,city,state,pincode,latitude,longitude FROM restaurants WHERE LOWER(COALESCE(name,'')) LIKE '%breado%' LIMIT 20`); for(const r of rs) await tryExec(`INSERT IGNORE INTO outlets(outlet_code,name,slug,address,city,state,pincode,latitude,longitude,is_open,is_active,service_radius_km) VALUES(:code,:name,:slug,:address,:city,:state,:pincode,:lat,:lng,1,1,5)`,{code:`MRB-${r.id}`,name:r.name||'Mr Breado',slug:slugify(`${r.name||'mr-breado'}-${r.id}`),address:r.address||'',city:r.city||'',state:r.state||'',pincode:r.pincode||'',lat:r.latitude||null,lng:r.longitude||null}); }
function mapOutlet(o, userLat=null, userLng=null){ const lat=o.latitude==null?null:Number(o.latitude), lng=o.longitude==null?null:Number(o.longitude); const dist=(userLat!=null&&userLng!=null&&lat!=null&&lng!=null)?Number(haversineKm(userLat,userLng,lat,lng).toFixed(2)):null; const radius=n(o.service_radius_km,5); return {id:o.id,outletId:o.id,outletCode:o.outlet_code,name:o.name||'Mr Breado',outletName:o.name||'Mr Breado',slug:o.slug,address:o.address||'',city:o.city||'',state:o.state||'',pincode:o.pincode||'',latitude:lat,longitude:lng,serviceRadiusKm:radius,distanceKm:dist,isServiceable:dist==null?true:dist<=radius,isOpen:bool(o.is_open),phone:o.phone||o.manager_phone||'',email:o.email||o.manager_email||'',managerName:o.manager_name||'',managerPhone:o.manager_phone||'',managerEmail:o.manager_email||'',bannerImage:o.banner_image||'',profileImage:o.profile_image||o.logo_image||'',logoImage:o.logo_image||o.profile_image||'',openingTime:o.opening_time||'',closingTime:o.closing_time||'',googleMapLink:o.google_map_link||''}; }
async function outletStockRows(id){ return await tryMany(`SELECT s.id, s.outlet_id outletId, s.product_id productId, s.stock_qty stockQuantity, s.min_stock_qty lowStockAlert, s.prep_time_minutes preparationMinutes, s.is_available isAvailable, s.unit_cost unitCost, s.selling_price sellingPrice, COALESCE(NULLIF(p.name,''),p.title,p.product_name,CONCAT('Food #',p.id)) productName, COALESCE(p.image_url,p.image,p.photo_url) imageUrl, COALESCE(NULLIF(s.selling_price,0),p.price,p.discounted_price,0) price, p.description, p.slug FROM outlet_product_stock s LEFT JOIN products p ON p.id=s.product_id WHERE s.outlet_id=:id ORDER BY productName`,{id}); }
async function productCatalog(){ return await tryMany(`SELECT id productId, id, COALESCE(NULLIF(name,''),title,product_name,CONCAT('Food #',id)) productName, COALESCE(image_url,image,photo_url) imageUrl, COALESCE(price,discounted_price,0) price, description, slug FROM products WHERE COALESCE(deleted,0)=0 ORDER BY productName LIMIT 500`); }
function mapOffer(o){ const enabled=bool(o.enabled,true) && (!o.valid_to || String(o.valid_to).slice(0,10) >= today()); return {id:o.id,title:o.title,name:o.title,subtitle:o.subtitle||'',description:o.description||'',imageUrl:o.image_url||o.image||'',image:o.image_url||o.image||'',couponEnabled:bool(o.coupon_enabled,false),couponCode:o.coupon_code||'',discountType:o.discount_type||'PERCENT',discountValue:n(o.discount_value),minOrderAmount:n(o.min_order_amount),maxDiscount:n(o.max_discount),validFrom:o.valid_from?String(o.valid_from).slice(0,10):'',validTo:o.valid_to?String(o.valid_to).slice(0,10):'',enabled,active:enabled,freeDelivery:(o.discount_type==='FREE_DELIVERY')}; }

router.get('/single-brand/v50/version',(req,res)=>ok(res,{version:'single-brand-enterprise-v50',model:'Mr Breado outlet ERP with practical offers, outlet stock assignment and branding',razorpay:'v22/v26 untouched'}));
router.post(['/admin/outlets/ensure-enterprise-v50-schema','/admin/outlets/ensure-enterprise-schema','/admin/outlets/ensure-schema'],ah(async(req,res)=>{ await seedOutlets(); ok(res,{ready:true,version:'v50'},'V50 enterprise schema ready'); }));

router.get(['/admin/outlets','/outlets','/user/outlets'],ah(async(req,res)=>{ await seedOutlets(); const lat=req.query.lat?Number(req.query.lat):null, lng=req.query.lng?Number(req.query.lng):null; const rows=await tryMany(`SELECT * FROM outlets WHERE COALESCE(is_active,1)=1 ORDER BY id DESC`); ok(res, rows.map(x=>mapOutlet(x,lat,lng)), 'Outlets fetched'); }));
router.post('/admin/outlets',ah(async(req,res)=>{ await ensureV50Schema(); const b=req.body||{}; const name=s(b.name||b.outletName||'Mr Breado').trim(); const code=s(b.outletCode||b.outlet_code||`MRB-${Date.now()}`).trim(); const result=await exec(`INSERT INTO outlets(outlet_code,name,slug,address,city,state,pincode,latitude,longitude,service_radius_km,phone,email,manager_name,manager_phone,manager_email,banner_image,profile_image,logo_image,is_open,is_active) VALUES(:code,:name,:slug,:address,:city,:state,:pincode,:lat,:lng,:radius,:phone,:email,:managerName,:managerPhone,:managerEmail,:banner,:profile,:logo,:open,1)`,{code,name,slug:slugify(b.slug||`${name}-${code}`),address:b.address||'',city:b.city||'',state:b.state||'',pincode:b.pincode||'',lat:b.latitude||null,lng:b.longitude||null,radius:b.serviceRadiusKm||b.service_radius_km||5,phone:b.phone||'',email:b.email||'',managerName:b.managerName||b.manager_name||'',managerPhone:b.managerPhone||b.manager_phone||'',managerEmail:b.managerEmail||b.manager_email||'',banner:b.bannerImage||b.banner_image||'',profile:b.profileImage||b.profile_image||'',logo:b.logoImage||b.logo_image||b.profileImage||'',open:b.isOpen===false?0:1}); ok(res,{id:result.insertId},'Outlet created',201); }));
router.put('/admin/outlets/:id',ah(async(req,res)=>{ await ensureV50Schema(); const b=req.body||{}; await exec(`UPDATE outlets SET name=COALESCE(:name,name), address=COALESCE(:address,address), city=COALESCE(:city,city), state=COALESCE(:state,state), pincode=COALESCE(:pincode,pincode), latitude=COALESCE(:lat,latitude), longitude=COALESCE(:lng,longitude), service_radius_km=COALESCE(:radius,service_radius_km), phone=COALESCE(:phone,phone), email=COALESCE(:email,email), manager_name=COALESCE(:managerName,manager_name), manager_phone=COALESCE(:managerPhone,manager_phone), manager_email=COALESCE(:managerEmail,manager_email), banner_image=COALESCE(:banner,banner_image), profile_image=COALESCE(:profile,profile_image), logo_image=COALESCE(:logo,logo_image), opening_time=COALESCE(:opening,opening_time), closing_time=COALESCE(:closing,closing_time), google_map_link=COALESCE(:map,google_map_link), is_open=COALESCE(:open,is_open) WHERE id=:id`,{id:req.params.id,name:b.name||b.outletName||null,address:b.address??null,city:b.city??null,state:b.state??null,pincode:b.pincode??null,lat:b.latitude??null,lng:b.longitude??null,radius:b.serviceRadiusKm??b.service_radius_km??null,phone:b.phone??null,email:b.email??null,managerName:b.managerName??b.manager_name??null,managerPhone:b.managerPhone??b.manager_phone??null,managerEmail:b.managerEmail??b.manager_email??null,banner:b.bannerImage??b.banner_image??null,profile:b.profileImage??b.profile_image??null,logo:b.logoImage??b.logo_image??null,opening:b.openingTime??b.opening_time??null,closing:b.closingTime??b.closing_time??null,map:b.googleMapLink??b.google_map_link??null,open:b.isOpen===undefined?null:(b.isOpen?1:0)}); ok(res,{id:req.params.id},'Outlet updated'); }));
router.post(['/admin/outlets/:id/branding','/admin/outlets/:id/set-location'],ah(async(req,res)=>{ req.url = `/admin/outlets/${req.params.id}`; await exec(`UPDATE outlets SET latitude=COALESCE(:lat,latitude), longitude=COALESCE(:lng,longitude), service_radius_km=COALESCE(:radius,service_radius_km), address=COALESCE(:address,address), banner_image=COALESCE(:banner,banner_image), profile_image=COALESCE(:profile,profile_image), logo_image=COALESCE(:logo,logo_image), phone=COALESCE(:phone,phone), email=COALESCE(:email,email), google_map_link=COALESCE(:map,google_map_link) WHERE id=:id`,{id:req.params.id,lat:req.body?.latitude??null,lng:req.body?.longitude??null,radius:req.body?.serviceRadiusKm??req.body?.service_radius_km??null,address:req.body?.address??null,banner:req.body?.bannerImage??null,profile:req.body?.profileImage??null,logo:req.body?.logoImage??null,phone:req.body?.phone??null,email:req.body?.email??null,map:req.body?.googleMapLink??null}); ok(res,{id:req.params.id},'Outlet profile/location saved'); }));
router.get('/outlets/nearest',ah(async(req,res)=>{ await seedOutlets(); const lat=req.query.lat?Number(req.query.lat):null, lng=req.query.lng?Number(req.query.lng):null, pincode=s(req.query.pincode); let rows=await tryMany(`SELECT * FROM outlets WHERE COALESCE(is_active,1)=1`); let mapped=rows.map(x=>mapOutlet(x,lat,lng)); if(lat!=null&&lng!=null) mapped=mapped.sort((a,b)=>(a.distanceKm??99999)-(b.distanceKm??99999)); else if(pincode) mapped=mapped.sort((a,b)=>(a.pincode===pincode?0:1)-(b.pincode===pincode?0:1)); const nearest=mapped.find(x=>x.isServiceable)||mapped[0]||null; ok(res,nearest,'Nearest outlet fetched'); }));
router.get(['/outlets/:id/menu','/user/outlets/:id/menu'],ah(async(req,res)=>{ await ensureV50Schema(); const stock=(await outletStockRows(req.params.id)).filter(x=>bool(x.isAvailable,true)&&n(x.stockQuantity)>0); ok(res,{outlet:mapOutlet(await tryOne(`SELECT * FROM outlets WHERE id=:id`,{id:req.params.id})||{}),items:stock,products:stock,foods:stock},'Outlet available menu fetched'); }));
router.get('/menu/nearest',ah(async(req,res)=>{ await seedOutlets(); const rows=await tryMany(`SELECT * FROM outlets WHERE COALESCE(is_active,1)=1`); const lat=req.query.lat?Number(req.query.lat):null,lng=req.query.lng?Number(req.query.lng):null; let mapped=rows.map(x=>mapOutlet(x,lat,lng)).sort((a,b)=>(a.distanceKm??99999)-(b.distanceKm??99999)); const outlet=mapped.find(x=>x.isServiceable)||mapped[0]; if(!outlet) return ok(res,{outlet:null,items:[]},'No outlet found'); const stock=(await outletStockRows(outlet.id)).filter(x=>bool(x.isAvailable,true)&&n(x.stockQuantity)>0); ok(res,{outlet,items:stock,products:stock,foods:stock},'Nearest outlet menu fetched'); }));
router.get('/admin/products/catalog',ah(async(req,res)=>{ ok(res,await productCatalog(),'Product catalog fetched'); }));
router.get('/admin/outlets/:id/available-products',ah(async(req,res)=>{ const assigned=await outletStockRows(req.params.id); const assignedIds=new Set(assigned.map(x=>Number(x.productId))); const all=await productCatalog(); ok(res,{assigned,unassigned:all.filter(x=>!assignedIds.has(Number(x.productId))),all},'Outlet product assignment data fetched'); }));
router.post('/admin/outlets/:id/stock',ah(async(req,res)=>{ await ensureV50Schema(); const items=Array.isArray(req.body?.items)?req.body.items:[req.body||{}]; for(const item of items){ const productId=item.productId||item.product_id||item.id; if(!productId) continue; const before=await tryOne(`SELECT stock_qty FROM outlet_product_stock WHERE outlet_id=:outletId AND product_id=:productId`,{outletId:req.params.id,productId}); const beforeQty=n(before?.stock_qty,0); const qty=n(item.stockQuantity??item.stock_qty??item.quantity??0); const min=n(item.lowStockAlert??item.minStockQty??item.min_stock_qty??5); const prep=n(item.preparationMinutes??item.prepTimeMinutes??item.prep_time_minutes??20); const price=n(item.sellingPrice??item.price??0); const cost=n(item.unitCost??item.unit_cost??0); await exec(`INSERT INTO outlet_product_stock(outlet_id,product_id,stock_qty,min_stock_qty,prep_time_minutes,is_available,unit_cost,selling_price) VALUES(:outletId,:productId,:qty,:min,:prep,:avail,:cost,:price) ON DUPLICATE KEY UPDATE stock_qty=:qty,min_stock_qty=:min,prep_time_minutes=:prep,is_available=:avail,unit_cost=:cost,selling_price=:price`,{outletId:req.params.id,productId,qty,min,prep,avail:item.isAvailable===false?0:1,cost,price}); await tryExec(`INSERT INTO outlet_stock_movements(outlet_id,product_id,movement_type,quantity,before_stock,after_stock,unit_cost,total_cost,note) VALUES(:outletId,:productId,'ADMIN_REFILL',:changeQty,:beforeQty,:qty,:cost,:total,:note)`,{outletId:req.params.id,productId,changeQty:qty-beforeQty,beforeQty,qty,cost,total:Math.max(0,qty-beforeQty)*cost,note:item.note||'Admin assigned/updated stock'}); } ok(res,{outletId:req.params.id,items},'Outlet stock saved'); }));
router.get('/admin/outlets/:id/full-dashboard',ah(async(req,res)=>{ await ensureV50Schema(); const outlet=mapOutlet(await tryOne(`SELECT * FROM outlets WHERE id=:id`,{id:req.params.id})||{}); const stock=await outletStockRows(req.params.id); const closing=await tryMany(`SELECT *, (online_sales+cod_sales+offline_sales) total_sales FROM outlet_daily_closings WHERE outlet_id=:id ORDER BY closing_date DESC LIMIT 370`,{id:req.params.id}); const movements=await tryMany(`SELECT m.*, COALESCE(NULLIF(p.name,''),p.title,p.product_name) productName FROM outlet_stock_movements m LEFT JOIN products p ON p.id=m.product_id WHERE m.outlet_id=:id ORDER BY m.created_at DESC LIMIT 100`,{id:req.params.id}); const best=await tryMany(`SELECT oi.product_id productId, COALESCE(NULLIF(p.name,''),p.title,p.product_name) productName, SUM(oi.quantity) soldQuantity, SUM(COALESCE(oi.total_price, oi.price*oi.quantity,0)) grossSales FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id LEFT JOIN orders o ON o.id=oi.order_id WHERE COALESCE(o.outlet_id,o.restaurant_id)=:id GROUP BY oi.product_id,productName ORDER BY soldQuantity DESC LIMIT 10`,{id:req.params.id}); const sales=closing.reduce((a,x)=>{a.totalSales+=n(x.total_sales);a.onlineSales+=n(x.online_sales);a.codSales+=n(x.cod_sales);a.offlineSales+=n(x.offline_sales);return a;},{totalSales:0,onlineSales:0,codSales:0,offlineSales:0}); const summary={...sales,orders:0,averageOrderValue:0,stockItems:stock.length,availableProducts:stock.filter(x=>bool(x.isAvailable,true)&&n(x.stockQuantity)>0).length,outOfStock:stock.filter(x=>n(x.stockQuantity)<=0).length,lowStock:stock.filter(x=>n(x.stockQuantity)<=n(x.lowStockAlert,5)).length,stockValue:stock.reduce((sum,x)=>sum+n(x.stockQuantity)*n(x.unitCost||x.price),0),todaySales:closing.filter(x=>String(x.closing_date).slice(0,10)===today()).reduce((sum,x)=>sum+n(x.total_sales),0),weekSales:sales.totalSales,monthSales:sales.totalSales,yearSales:sales.totalSales}; ok(res,{outlet,summary,stock,stockMovements:movements,movements,bestFoods:best,bestSelling:best,slowFoods:stock.filter(x=>n(x.stockQuantity)>0).sort((a,b)=>n(a.stockQuantity)-n(b.stockQuantity)).slice(0,10),slowSelling:stock.slice(0,10),closingCalendar:closing,dailyClosing:closing[0]||{}},'Outlet command center fetched'); }));

router.get(['/admin/offers','/offers','/user/offers'],ah(async(req,res)=>{ await ensureV50Schema(); await tryExec(`UPDATE offers SET enabled=0 WHERE valid_to IS NOT NULL AND valid_to<CURDATE()`); const rows=await tryMany(`SELECT * FROM offers ORDER BY id DESC`); const items=rows.map(mapOffer); ok(res,{items,total:items.length,total_pages:1,page:1},'Offers fetched'); }));
router.post('/admin/offers',ah(async(req,res)=>{ await ensureV50Schema(); const b=req.body||{}; const result=await exec(`INSERT INTO offers(title,subtitle,description,image_url,coupon_enabled,coupon_code,discount_type,discount_value,min_order_amount,max_discount,valid_from,valid_to,enabled) VALUES(:title,:subtitle,:description,:image,:couponEnabled,:code,:type,:value,:min,:max,:from,:to,:enabled)`,{title:b.title||b.name||'Mr Breado Offer',subtitle:b.subtitle||'',description:b.description||'',image:b.imageUrl||b.image||b.banner||'',couponEnabled:b.couponEnabled||b.coupon_enabled?1:0,code:s(b.couponCode||b.coupon_code).toUpperCase()||null,type:b.discountType||b.discount_type||'PERCENT',value:b.discountValue??b.discount_value??0,min:b.minOrderAmount??b.min_order_amount??0,max:b.maxDiscount??b.max_discount??0,from:dateOrNull(b.validFrom||b.valid_from),to:dateOrNull(b.validTo||b.valid_to),enabled:b.enabled===false?0:1}); if(b.couponEnabled||b.coupon_enabled){ const code=s(b.couponCode||b.coupon_code).toUpperCase(); if(code) await tryExec(`INSERT INTO coupon_rules(code,title,description,coupon_type,discount_value,min_order_amount,max_discount,start_date,end_date,is_active) VALUES(:code,:title,:description,:type,:value,:min,:max,:from,:to,:enabled) ON DUPLICATE KEY UPDATE title=:title,description=:description,coupon_type=:type,discount_value=:value,min_order_amount=:min,max_discount=:max,start_date=:from,end_date=:to,is_active=:enabled`,{code,title:b.title||'',description:b.description||'',type:b.discountType||'PERCENT',value:b.discountValue||0,min:b.minOrderAmount||0,max:b.maxDiscount||0,from:dateOrNull(b.validFrom),to:dateOrNull(b.validTo),enabled:b.enabled===false?0:1}); } ok(res,{id:result.insertId},'Offer created',201); }));
router.put('/admin/offers/:id',ah(async(req,res)=>{ await ensureV50Schema(); const b=req.body||{}; await exec(`UPDATE offers SET title=:title,subtitle=:subtitle,description=:description,image_url=:image,coupon_enabled=:couponEnabled,coupon_code=:code,discount_type=:type,discount_value=:value,min_order_amount=:min,max_discount=:max,valid_from=:from,valid_to=:to,enabled=:enabled WHERE id=:id`,{id:req.params.id,title:b.title||b.name||'',subtitle:b.subtitle||'',description:b.description||'',image:b.imageUrl||b.image||b.banner||'',couponEnabled:b.couponEnabled||b.coupon_enabled?1:0,code:s(b.couponCode||b.coupon_code).toUpperCase()||null,type:b.discountType||b.discount_type||'PERCENT',value:b.discountValue??b.discount_value??0,min:b.minOrderAmount??b.min_order_amount??0,max:b.maxDiscount??b.max_discount??0,from:dateOrNull(b.validFrom||b.valid_from),to:dateOrNull(b.validTo||b.valid_to),enabled:b.enabled===false?0:1}); ok(res,{id:req.params.id},'Offer updated'); }));
router.patch('/admin/offers/:id/status',ah(async(req,res)=>{ await ensureV50Schema(); const row=await tryOne(`SELECT enabled FROM offers WHERE id=:id`,{id:req.params.id}); const enabled=req.body?.enabled===undefined?(bool(row?.enabled,true)?0:1):(req.body.enabled?1:0); await exec(`UPDATE offers SET enabled=:enabled WHERE id=:id`,{id:req.params.id,enabled}); ok(res,{id:req.params.id,enabled},'Offer status updated'); }));
router.delete('/admin/offers/:id',ah(async(req,res)=>{ await ensureV50Schema(); await tryExec(`DELETE FROM offers WHERE id=:id`,{id:req.params.id}); ok(res,{id:req.params.id},'Offer deleted'); }));

router.post(['/coupons/validate','/checkout/coupons/validate'],ah(async(req,res)=>{ await ensureV50Schema(); const code=s(req.body?.code).toUpperCase(); const amount=n(req.body?.amount||req.body?.cartTotal); const coupon=await tryOne(`SELECT * FROM coupon_rules WHERE code=:code AND is_active=1 AND (start_date IS NULL OR start_date<=CURDATE()) AND (end_date IS NULL OR end_date>=CURDATE())`,{code}); if(!coupon) return res.status(400).json({success:false,message:'Coupon is invalid or expired'}); if(amount<n(coupon.min_order_amount)) return res.status(400).json({success:false,message:`Minimum order amount ₹${coupon.min_order_amount} required`}); let discount=0, freeDelivery=false; if(coupon.coupon_type==='FREE_DELIVERY') freeDelivery=true; else if(coupon.coupon_type==='PERCENT'){ discount=amount*n(coupon.discount_value)/100; if(n(coupon.max_discount)>0) discount=Math.min(discount,n(coupon.max_discount)); } else discount=n(coupon.discount_value); ok(res,{coupon,discount:Number(discount.toFixed(2)),freeDelivery,deliveryFee:freeDelivery?0:null},'Coupon applied'); }));

router.use(require('./singleBrandEnterpriseV49'));
module.exports = router;
