const router = require('express').Router();
const { ok, fail } = require('../utils/respond');
const ah = require('../utils/asyncHandler');
const { optionalAuth } = require('../middleware/auth');
const { pool } = require('../utils/db');

const cache = new Map();
async function cols(table){ if(cache.has(table)) return cache.get(table); try{ const [r]=await pool.execute(`SHOW COLUMNS FROM \`${table}\``); const s=new Set(r.map(x=>x.Field)); cache.set(table,s); return s; }catch{ const s=new Set(); cache.set(table,s); return s; } }
async function exists(t){ return (await cols(t)).size>0; }
async function q(sql, params=[]){ try{ const [r]=await pool.execute(sql, params); return r; }catch(e){ console.error('[v33 query]', e.message, sql); return []; } }
async function one(sql, params=[]){ const r=await q(sql,params); return r[0]||null; }
async function run(sql, params=[]){ try{ const [r]=await pool.execute(sql,params); return r; }catch(e){ console.error('[v33 exec]', e.message, sql); return {affectedRows:0}; } }
function bool(v,d=false){ if(v==null)return d; if(Buffer.isBuffer(v))return v[0]===1; if(typeof v==='object'&&Array.isArray(v.data))return Number(v.data[0])===1; if(typeof v==='boolean')return v; if(typeof v==='number')return v===1; return ['1','true','yes','on','active','available','verified','approved'].includes(String(v).toLowerCase()); }
function num(v,d=0){ const n=Number(v); return Number.isFinite(n)?n:d; }
function first(...vals){ for(const v of vals){ if(v!==undefined&&v!==null&&String(v).trim()!=='') return v; } return undefined; }
function text(v,d=''){ return String(v??d).trim(); }
function safeName(v){ return String(v||'document').replace(/["\r\n]/g,'').replace(/[/\\]/g,'_'); }
function abs(req,path){ if(!path)return ''; if(/^https?:\/\//i.test(path))return path; if(String(path).startsWith('/')) return `${req.protocol}://${req.get('host')}${path}`; return `${req.protocol}://${req.get('host')}/api/admin/verifications/files/${encodeURIComponent(path)}`; }
function page(items, req){ const p=Math.max(1,num(req.query.page,1)); const per=Math.max(1,num(req.query.perPage||req.query.per_page||req.query.limit, items.length||20)); return {success:true,items,data:items,content:items,records:items,drivers:items,requests:items,verifications:items,total:items.length,totalItems:items.length,totalElements:items.length,page:p,currentPage:p,perPage:per,per_page:per,totalPages:Math.max(1,Math.ceil(items.length/per)),total_pages:Math.max(1,Math.ceil(items.length/per)),last:true}; }
function parse(v){ if(!v)return {}; if(typeof v==='object') return v; try{return JSON.parse(String(v));}catch{return{};} }
function payFields(row={}, payload={}){ return {
  upiId:first(row.upi_id,row.upiId,payload.upiId,payload.upi_id,payload.upi,''),
  bankName:first(row.bank_name,row.bankName,payload.bankName,payload.bank_name,''),
  bankAccountName:first(row.bank_account_name,row.bankAccountName,payload.bankAccountName,payload.accountHolderName,payload.account_holder_name,''),
  bankAccountNumber:first(row.bank_account_number,row.bankAccountNumber,payload.bankAccountNumber,payload.accountNumber,payload.account_number,''),
  bankIfsc:first(row.bank_ifsc,row.bankIfsc,payload.bankIfsc,payload.ifsc,payload.ifscCode,payload.ifsc_code,''),
}; }
async function ensurePayoutColumns(){
  for(const t of ['verification_requests','delivery_partner_profiles','restaurants']){
    const c=await cols(t); if(!c.size) continue;
    const adds=[];
    if(!c.has('upi_id')) adds.push('ADD COLUMN upi_id varchar(255) NULL');
    if(!c.has('bank_name')) adds.push('ADD COLUMN bank_name varchar(255) NULL');
    if(!c.has('bank_account_name')) adds.push('ADD COLUMN bank_account_name varchar(255) NULL');
    if(!c.has('bank_account_number')) adds.push('ADD COLUMN bank_account_number varchar(255) NULL');
    if(!c.has('bank_ifsc')) adds.push('ADD COLUMN bank_ifsc varchar(255) NULL');
    if(adds.length){ await run(`ALTER TABLE \`${t}\` ${adds.join(', ')}`); cache.delete(t); }
  }
}
ensurePayoutColumns().catch(()=>{});

async function docsFor(req, source, id){
  if(source==='native' && await exists('verification_documents')){
    const rows=await q('SELECT * FROM verification_documents WHERE request_id=? ORDER BY id',[id]);
    return rows.map(d=>({id:d.id,requestId:id,source:'native',documentType:first(d.document_type,d.content_type,'DOCUMENT'),type:first(d.document_type,d.content_type,'DOCUMENT'),name:first(d.original_filename,d.document_type,`Document ${d.id}`),originalName:first(d.original_filename,`Document ${d.id}`),originalFilename:first(d.original_filename,`Document ${d.id}`),fileName:first(d.original_filename,`Document ${d.id}`),mimeType:first(d.content_type,'image/jpeg'),fileSize:num(d.size_bytes),uploadedAt:d.uploaded_at,url:abs(req,`/api/admin/verifications/native-${id}/documents/${d.id}/view`),fileUrl:abs(req,`/api/admin/verifications/native-${id}/documents/${d.id}/view`),viewUrl:abs(req,`/api/admin/verifications/native-${id}/documents/${d.id}/view`),downloadUrl:abs(req,`/api/admin/verifications/native-${id}/documents/${d.id}/download`),rawFileUrl:d.file_url||''}));
  }
  if(source==='app' && await exists('app_verification_documents')){
    const rows=await q('SELECT * FROM app_verification_documents WHERE request_id=? ORDER BY id',[id]);
    return rows.map(d=>({id:d.id,requestId:id,source:'app',documentType:first(d.document_type,d.mime_type,'DOCUMENT'),type:first(d.document_type,d.mime_type,'DOCUMENT'),name:first(d.original_name,d.document_type,`Document ${d.id}`),originalName:first(d.original_name,`Document ${d.id}`),originalFilename:first(d.original_name,`Document ${d.id}`),fileName:first(d.original_name,`Document ${d.id}`),mimeType:first(d.mime_type,'image/jpeg'),fileSize:num(d.file_size),uploadedAt:d.created_at,url:abs(req,`/api/admin/verifications/app-${id}/documents/${d.id}/view`),fileUrl:abs(req,`/api/admin/verifications/app-${id}/documents/${d.id}/view`),viewUrl:abs(req,`/api/admin/verifications/app-${id}/documents/${d.id}/view`),downloadUrl:abs(req,`/api/admin/verifications/app-${id}/documents/${d.id}/download`)}));
  }
  return [];
}

async function loadNative(req){
  if(!await exists('verification_requests')) return [];
  const rows=await q(`SELECT vr.*, u.name user_name, u.email user_email, COALESCE(u.mobile,u.phone_number) user_mobile,
    r.name restaurant_name, r.restaurant_name restaurant_name2, r.owner_id,
    dp.id profile_id, dp.user_id rider_user_id, du.name rider_user_name, du.email rider_user_email, COALESCE(du.mobile,du.phone_number) rider_user_mobile
    FROM verification_requests vr
    LEFT JOIN users u ON u.id=vr.target_id
    LEFT JOIN restaurants r ON r.id=vr.target_id AND vr.target_type='RESTAURANT'
    LEFT JOIN delivery_partner_profiles dp ON (dp.id=vr.target_id OR dp.user_id=vr.target_id) AND vr.target_type='RIDER'
    LEFT JOIN users du ON du.id=dp.user_id
    ORDER BY vr.created_at DESC, vr.id DESC LIMIT 500`);
  const out=[];
  for(const r of rows){ const kind=String(r.target_type||'RIDER').toUpperCase(); const docs=await docsFor(req,'native',r.id); const payload={}; const pay=payFields(r,payload); const name=kind==='RESTAURANT'?first(r.business_name,r.restaurant_name,r.restaurant_name2,r.applicant_name,r.user_name,`Restaurant #${r.target_id}`):first(r.applicant_name,r.rider_user_name,r.user_name,`Rider #${r.target_id}`); out.push({...r,id:`native-${r.id}`,numericId:r.id,requestId:`native-${r.id}`,source:'native',sourceTable:'verification_requests',requesterType:kind,entityType:kind,requestType:kind,status:String(r.status||'PENDING').toUpperCase(),userId:kind==='RIDER'?first(r.rider_user_id,r.target_id):first(r.owner_id,r.target_id),riderId:kind==='RIDER'?first(r.profile_id,r.target_id):null,driverId:kind==='RIDER'?first(r.profile_id,r.target_id):null,restaurantId:kind==='RESTAURANT'?r.target_id:null,applicantName:name,fullName:name,ownerName:first(r.owner_name,r.applicant_name,r.user_name,name),businessName:kind==='RESTAURANT'?first(r.business_name,r.restaurant_name,r.restaurant_name2,name):'',restaurantName:kind==='RESTAURANT'?first(r.restaurant_name,r.restaurant_name2,r.business_name,name):'',riderName:kind==='RIDER'?name:undefined,driverName:kind==='RIDER'?name:undefined,contactMobile:first(r.contact_mobile,r.rider_user_mobile,r.user_mobile,''),mobile:first(r.contact_mobile,r.rider_user_mobile,r.user_mobile,''),phone:first(r.contact_mobile,r.rider_user_mobile,r.user_mobile,''),email:first(r.user_email,r.rider_user_email,''),address:first(r.address,r.applicant_note,''),note:first(r.applicant_note,r.address,''),gstin:first(r.gstin,''),panNumber:first(r.pan_number,''),fssaiNumber:first(r.fssai_number,''),aadhaarNumber:first(r.aadhaar_number,''),drivingLicenseNumber:first(r.driving_license_number,''),vehicleRegistrationNumber:first(r.vehicle_registration_number,''),...pay,documents:docs,createdAt:r.created_at,updatedAt:r.updated_at}); }
  return out;
}
async function loadApp(req){
  if(!await exists('app_verification_requests')) return [];
  const rows=await q(`SELECT vr.*, u.name user_name, u.email user_email, COALESCE(u.mobile,u.phone_number) user_mobile, r.name restaurant_name, r.restaurant_name restaurant_name2 FROM app_verification_requests vr LEFT JOIN users u ON u.id=vr.user_id LEFT JOIN restaurants r ON r.id=vr.restaurant_id ORDER BY vr.created_at DESC, vr.id DESC LIMIT 500`);
  const out=[];
  for(const r of rows){ const payload=parse(r.submitted_payload); const kind=String(first(r.requester_type,payload.requesterType,payload.type,'RIDER')).toUpperCase().includes('RESTAURANT')?'RESTAURANT':'RIDER'; const docs=await docsFor(req,'app',r.id); const pay=payFields(r,payload); const name=kind==='RESTAURANT'?first(r.business_name,r.restaurant_name,r.restaurant_name2,payload.businessName,payload.restaurantName,payload.storeName,r.user_name,`Restaurant request #${r.id}`):first(r.owner_name,r.user_name,payload.fullName,payload.name,payload.driverName,payload.riderName,`Rider request #${r.id}`); out.push({...r,id:`app-${r.id}`,numericId:r.id,requestId:`app-${r.id}`,source:'app',sourceTable:'app_verification_requests',requesterType:kind,entityType:kind,requestType:kind,status:String(r.status||'PENDING').toUpperCase(),userId:r.user_id,riderId:first(r.rider_id,r.user_id),driverId:first(r.rider_id,r.user_id),restaurantId:r.restaurant_id,applicantName:name,fullName:name,ownerName:first(r.owner_name,payload.ownerName,name),businessName:kind==='RESTAURANT'?first(r.business_name,r.restaurant_name,r.restaurant_name2,payload.businessName,payload.restaurantName,name):'',restaurantName:kind==='RESTAURANT'?first(r.restaurant_name,r.restaurant_name2,r.business_name,payload.restaurantName,name):'',riderName:kind==='RIDER'?name:undefined,driverName:kind==='RIDER'?name:undefined,contactMobile:first(r.phone,r.user_mobile,payload.mobile,payload.phone,payload.phoneNumber,''),mobile:first(r.phone,r.user_mobile,payload.mobile,payload.phone,payload.phoneNumber,''),phone:first(r.phone,r.user_mobile,payload.mobile,payload.phone,payload.phoneNumber,''),email:first(r.email,r.user_email,payload.email,''),address:first(r.notes,payload.address,payload.fullAddress,payload.residentialAddress,payload.restaurantAddress,''),note:first(r.notes,payload.notes,payload.note,''),gstin:first(payload.gstin,payload.gstNumber,''),panNumber:first(payload.panNumber,payload.pan,payload.panCardNo,''),fssaiNumber:first(payload.fssaiNumber,payload.fssaiLicense,payload.fssai,''),aadhaarNumber:first(payload.aadhaarNumber,payload.aadharNumber,payload.aadhaarNo,payload.aadharNo,''),drivingLicenseNumber:first(payload.drivingLicenseNumber,payload.drivingLicense,payload.licenseNumber,payload.dlNumber,''),vehicleRegistrationNumber:first(payload.vehicleRegistrationNumber,payload.vehicleRcNumber,payload.vehicleRc,payload.vehicleNumber,payload.rcNumber,''),...pay,documents:docs,createdAt:first(r.created_at,r.createdAt),updatedAt:first(r.updated_at,r.updatedAt),submittedPayload:payload}); }
  return out;
}
async function allVerifications(req){ return [...await loadNative(req), ...await loadApp(req)]; }

function mapDriver(r){ const pending=String(first(r.pending_request_status,'')).toUpperCase()==='PENDING'; const v=pending?'PENDING':String(first(r.profile_verification_status,r.verification_status,r.verificationStatus,r.status,r.verified?'VERIFIED':'UNVERIFIED')).toUpperCase(); const name=first(r.user_name,r.name,r.full_name,r.driver_name,r.rider_name,`Rider #${first(r.user_id,r.id)}`); const mob=first(r.user_mobile,r.mobile,r.phone,r.phone_number,r.driver_mobile,'—'); const cash=num(first(r.cash_in_hand,r.pending_cash,r.total_cash_collected),0); const lim=num(first(r.cash_limit,r.cash_limit_amount),2000); return {...r,id:first(r.user_id,r.id),userId:first(r.user_id,r.id),profileId:first(r.profile_id,r.id),driverId:first(r.profile_id,r.id,r.user_id),driverName:name,name,driverMobile:mob,mobile:mob,phone:mob,driverEmail:first(r.user_email,r.email,''),email:first(r.user_email,r.email,''),online:bool(first(r.online,r.is_online,r.available),false),available:bool(first(r.available,r.online),false),blocked:bool(r.blocked,false),enabled:bool(r.enabled,true),verified:['VERIFIED','APPROVED'].includes(v),verificationStatus:v,pendingVerification:pending,verificationRequestId:first(r.pending_request_id,''),totalDeliveries:num(first(r.total_deliveries,r.deliveries,r.delivery_count),0),totalEarnings:num(first(r.total_earnings,r.earnings),0),cashInHand:cash,cashLimit:lim,remainingLimit:Math.max(0,lim-cash),rating:num(first(r.rating,r.average_rating),0),vehicleNumber:first(r.vehicle_number,r.vehicleRegistrationNumber,''),drivingLicenseNumber:first(r.driving_license_number,r.drivingLicenseNumber,''),upiId:first(r.upi_id,''),bankName:first(r.bank_name,''),bankAccountNumber:first(r.bank_account_number,''),bankIfsc:first(r.bank_ifsc,''),createdAt:r.created_at}; }

router.use(optionalAuth);
router.get(['/admin/drivers','/admin/delivery-boys','/delivery-boys','/admin/riders'], ah(async(req,res)=>{
  const dc=await cols('delivery_partner_profiles'), uc=await cols('users'); let rows=[];
  if(dc.size){ const joinUser=uc.size?'LEFT JOIN users u ON u.id=dp.user_id':''; const vr=await exists('verification_requests'); const avr=await exists('app_verification_requests'); rows=await q(`SELECT dp.* , dp.id profile_id ${uc.size?', u.id user_id, u.name user_name, u.email user_email, COALESCE(u.mobile,u.phone_number) user_mobile, u.enabled, u.blocked, u.deleted, u.role':''} ${vr?', nvr.id native_pending_id, nvr.status native_pending_status':''} ${avr?', avr.id app_pending_id, avr.status app_pending_status':''}, COALESCE(${vr?'nvr.id':'NULL'}, ${avr?'avr.id':'NULL'}) pending_request_id, COALESCE(${vr?'nvr.status':'NULL'}, ${avr?'avr.status':'NULL'}) pending_request_status FROM delivery_partner_profiles dp ${joinUser} ${vr?"LEFT JOIN verification_requests nvr ON nvr.target_type='RIDER' AND UPPER(nvr.status)='PENDING' AND (nvr.target_id=dp.id OR nvr.target_id=dp.user_id)":''} ${avr?"LEFT JOIN app_verification_requests avr ON avr.requester_type='RIDER' AND UPPER(avr.status)='PENDING' AND (avr.user_id=dp.user_id OR avr.rider_id=dp.id)":''} ORDER BY CASE WHEN COALESCE(${vr?'nvr.id':'NULL'}, ${avr?'avr.id':'NULL'}) IS NULL THEN 1 ELSE 0 END, dp.id DESC LIMIT 500`); }
  if(!rows.length && uc.size) rows=await q("SELECT id user_id, name user_name, email user_email, COALESCE(mobile,phone_number) user_mobile, role, enabled, blocked, deleted FROM users WHERE UPPER(role) IN ('DELIVERY_PARTNER','RIDER','DRIVER','DELIVERY','DELIVERY_BOY') OR UPPER(role) LIKE '%DELIVERY%' ORDER BY id DESC LIMIT 500");
  const search=text(req.query.search).toLowerCase(); let items=rows.map(mapDriver); if(search) items=items.filter(x=>`${x.driverName} ${x.driverMobile} ${x.driverEmail} ${x.driverId} ${x.userId}`.toLowerCase().includes(search)); ok(res,page(items,req),'Drivers loaded');
}));
router.get(['/admin/verifications','/admin/verification-requests','/admin/verifications/all','/admin/service-area-verifications','/admin/drivers/verification-requests'], ah(async(req,res)=>{ let items=await allVerifications(req); const st=text(req.query.status).toUpperCase(); const type=text(req.query.targetType||req.query.target_type||req.query.type).toUpperCase(); const includeAll=['1','true','yes'].includes(text(req.query.includeAll||req.query.all).toLowerCase()); const status=st || (includeAll?'':'PENDING'); if(status) items=items.filter(x=>String(x.status).toUpperCase()===status || (status==='APPROVED'&&String(x.status).toUpperCase()==='VERIFIED')); if(type&&type!=='ALL') items=items.filter(x=>String(x.requesterType).toUpperCase()===type || (type==='DRIVER'&&x.requesterType==='RIDER')); ok(res,page(items,req),'Verification requests loaded'); }));
router.get('/admin/verifications/:id', ah(async(req,res)=>{ const id=String(req.params.id); const item=(await allVerifications(req)).find(x=>String(x.id)===id||String(x.numericId)===id||String(x.requestId)===id); if(!item) return fail(res,'Verification request not found',404); ok(res,item,'Verification request loaded'); }));
async function updateVerification(req,res,status){ const raw=String(req.params.id); const src=raw.startsWith('app-')?'app':'native'; const id=Number(raw.replace(/^(native-|app-)/,'')); if(!Number.isFinite(id)) return fail(res,'Invalid verification request id',400); const approved=['APPROVED','VERIFIED'].includes(status); if(src==='native'){ const row=await one('SELECT * FROM verification_requests WHERE id=?',[id]); if(!row)return fail(res,'Verification request not found',404); const ns=approved?'VERIFIED':'REJECTED'; await run('UPDATE verification_requests SET status=?, admin_remark=?, reviewed_at=NOW(6), updated_at=NOW(6) WHERE id=?',[ns,text(req.body?.reason||req.body?.note,''),id]); if(String(row.target_type).toUpperCase()==='RIDER') await run('UPDATE delivery_partner_profiles SET verification_status=?, verified=?, updated_at=NOW(6) WHERE id=? OR user_id=?',[ns,approved?1:0,row.target_id,row.target_id]); else await run("UPDATE restaurants SET verification_status=?, verified=?, visibility_status=CASE WHEN ?=1 THEN 'VISIBLE' ELSE visibility_status END, updated_at=NOW(6) WHERE id=?",[approved?'APPROVED':'REJECTED',approved?1:0,approved?1:0,row.target_id]); return ok(res,{id:raw,status:ns},`Verification ${ns.toLowerCase()}`); } const row=await one('SELECT * FROM app_verification_requests WHERE id=?',[id]); if(!row)return fail(res,'Verification request not found',404); const ns=approved?'APPROVED':'REJECTED'; await run('UPDATE app_verification_requests SET status=?, rejection_reason=?, updated_at=NOW(6) WHERE id=?',[ns,text(req.body?.reason||req.body?.note,''),id]); if(String(row.requester_type).toUpperCase()==='RIDER') await run('UPDATE delivery_partner_profiles SET verification_status=?, verified=?, updated_at=NOW(6) WHERE user_id=? OR id=?',[approved?'VERIFIED':'REJECTED',approved?1:0,row.user_id,row.rider_id||row.user_id]); else await run("UPDATE restaurants SET verification_status=?, verified=?, visibility_status=CASE WHEN ?=1 THEN 'VISIBLE' ELSE visibility_status END, updated_at=NOW(6) WHERE id=? OR owner_id=?",[approved?'APPROVED':'REJECTED',approved?1:0,approved?1:0,row.restaurant_id||0,row.user_id||0]); ok(res,{id:raw,status:ns},`Verification ${ns.toLowerCase()}`); }
router.post('/admin/verifications/:id/approve', ah((req,res)=>updateVerification(req,res,'APPROVED')));
router.post('/admin/verifications/:id/reject', ah((req,res)=>updateVerification(req,res,'REJECTED')));
router.patch('/admin/verifications/:id/status', ah((req,res)=>updateVerification(req,res,String(req.body?.status||req.query.status||'APPROVED').toUpperCase())));
async function streamRemote(res,url,disp,name){ const r=await fetch(url); if(!r.ok) return false; res.setHeader('Content-Type',r.headers.get('content-type')||'application/octet-stream'); res.setHeader('Content-Disposition',`${disp}; filename="${safeName(name)}"`); const ab=await r.arrayBuffer(); res.end(Buffer.from(ab)); return true; }
router.get('/admin/verifications/:id/documents/:documentId/view', ah(async(req,res)=>{ const raw=String(req.params.id); const src=raw.startsWith('app-')?'app':'native'; const rid=Number(raw.replace(/^(native-|app-)/,'')); const did=Number(req.params.documentId); if(src==='native'){ const d=await one('SELECT * FROM verification_documents WHERE id=? AND request_id=?',[did,rid]); if(!d)return fail(res,'Document not found',404); const url=d.file_url||''; if(/^https?:\/\//i.test(url)){ if(await streamRemote(res,url,'inline',d.original_filename)) return; return res.redirect(url); } if(url.startsWith('/')) return res.redirect(url); return fail(res,'Document file URL is not available from storage. Please re-upload this document.',404); } const d=await one('SELECT * FROM app_verification_documents WHERE id=? AND request_id=?',[did,rid]); if(!d)return fail(res,'Document not found',404); res.setHeader('Content-Type',d.mime_type||'application/octet-stream'); res.setHeader('Content-Disposition',`inline; filename="${safeName(d.original_name)}"`); res.end(d.file_blob); }));
router.get('/admin/verifications/:id/documents/:documentId/download', ah(async(req,res)=>{ const raw=String(req.params.id); const src=raw.startsWith('app-')?'app':'native'; const rid=Number(raw.replace(/^(native-|app-)/,'')); const did=Number(req.params.documentId); if(src==='native'){ const d=await one('SELECT * FROM verification_documents WHERE id=? AND request_id=?',[did,rid]); if(!d)return fail(res,'Document not found',404); if(/^https?:\/\//i.test(d.file_url||'')){ if(await streamRemote(res,d.file_url,'attachment',d.original_filename)) return; return res.redirect(d.file_url); } return fail(res,'Document file URL is not available from storage. Please re-upload this document.',404); } const d=await one('SELECT * FROM app_verification_documents WHERE id=? AND request_id=?',[did,rid]); if(!d)return fail(res,'Document not found',404); res.setHeader('Content-Type',d.mime_type||'application/octet-stream'); res.setHeader('Content-Disposition',`attachment; filename="${safeName(d.original_name)}"`); res.end(d.file_blob); }));

module.exports = router;
